/*!
 *  Copyright (c) 2021 American Mathematical Society
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

import { Configuration } from "mathjax-full/mjs/input/tex/Configuration.js";
import {
  CommandMap,
  CharacterMap,
  DelimiterMap,
} from "mathjax-full/mjs/input/tex/SymbolMap.js";
import { ParseMethod } from "mathjax-full/mjs/input/tex/Types.js";
import ParseMethods from "mathjax-full/mjs/input/tex/ParseMethods.js";
import BaseMethods from "mathjax-full/mjs/input/tex/base/BaseMethods.js";

import { TEXCLASS } from "mathjax-full/mjs/core/MmlTree/MmlNode.js";

let unicodeMathMethods: Record<string, ParseMethod> = {};

unicodeMathMethods.Macro = BaseMethods.Macro;
unicodeMathMethods.Accent = BaseMethods.Accent;
unicodeMathMethods.UnderOver = BaseMethods.UnderOver;
unicodeMathMethods.Not = BaseMethods.Not;

new CharacterMap("unicode-math-mathchar0mi", ParseMethods.mathchar0mi, {
  // \mathalpha
  Angstrom: "\u{212B}",
  BbbA: "\u{1D538}",
  BbbB: "\u{1D539}",
  BbbC: "\u{2102}",
  BbbD: "\u{1D53B}",
  BbbE: "\u{1D53C}",
  BbbF: "\u{1D53D}",
  BbbG: "\u{1D53E}",
  BbbGamma: "\u{213E}",
  BbbH: "\u{210D}",
  BbbI: "\u{1D540}",
  BbbJ: "\u{1D541}",
  BbbK: "\u{1D542}",
  BbbL: "\u{1D543}",
  BbbM: "\u{1D544}",
  BbbN: "\u{2115}",
  BbbO: "\u{1D546}",
  BbbP: "\u{2119}",
  BbbPi: "\u{213F}",
  BbbQ: "\u{211A}",
  BbbR: "\u{211D}",
  BbbS: "\u{1D54A}",
  BbbT: "\u{1D54B}",
  BbbU: "\u{1D54C}",
  BbbV: "\u{1D54D}",
  BbbW: "\u{1D54E}",
  BbbX: "\u{1D54F}",
  BbbY: "\u{1D550}",
  BbbZ: "\u{2124}",
  Bbba: "\u{1D552}",
  Bbbb: "\u{1D553}",
  Bbbc: "\u{1D554}",
  Bbbd: "\u{1D555}",
  Bbbe: "\u{1D556}",
  Bbbf: "\u{1D557}",
  Bbbg: "\u{1D558}",
  Bbbgamma: "\u{213D}",
  Bbbh: "\u{1D559}",
  Bbbi: "\u{1D55A}",
  Bbbj: "\u{1D55B}",
  Bbbk: "\u{1D55C}",
  Bbbl: "\u{1D55D}",
  Bbbm: "\u{1D55E}",
  Bbbn: "\u{1D55F}",
  Bbbo: "\u{1D560}",
  Bbbp: "\u{1D561}",
  Bbbq: "\u{1D562}",
  Bbbr: "\u{1D563}",
  Bbbs: "\u{1D564}",
  Bbbt: "\u{1D565}",
  Bbbu: "\u{1D566}",
  Bbbv: "\u{1D567}",
  Bbbw: "\u{1D568}",
  Bbbx: "\u{1D569}",
  Bbby: "\u{1D56A}",
  Bbbz: "\u{1D56B}",
  Im: "\u{2111}",
  Re: "\u{211C}",
  aleph: "\u{2135}",
  beth: "\u{2136}",
  daleth: "\u{2138}",
  ell: "\u{2113}",
  gimel: "\u{2137}",
  hslash: "\u{210F}",
  imath: "\u{1D6A4}",
  // NOTE MathJax maps jmath to u0237 (text dotless j); spacing differs with STIX2
  jmath: "\u{1D6A5}",
  matheth: "\u{00F0}",
  mathhyphen: "\u{2010}",
  mbfA: "\u{1D400}",
  mbfAlpha: "\u{1D6A8}",
  mbfB: "\u{1D401}",
  mbfBeta: "\u{1D6A9}",
  mbfC: "\u{1D402}",
  mbfChi: "\u{1D6BE}",
  mbfD: "\u{1D403}",
  mbfDelta: "\u{1D6AB}",
  mbfDigamma: "\u{1D7CA}",
  mbfE: "\u{1D404}",
  mbfEpsilon: "\u{1D6AC}",
  mbfEta: "\u{1D6AE}",
  mbfF: "\u{1D405}",
  mbfG: "\u{1D406}",
  mbfGamma: "\u{1D6AA}",
  mbfH: "\u{1D407}",
  mbfI: "\u{1D408}",
  mbfIota: "\u{1D6B0}",
  mbfJ: "\u{1D409}",
  mbfK: "\u{1D40A}",
  mbfKappa: "\u{1D6B1}",
  mbfL: "\u{1D40B}",
  mbfLambda: "\u{1D6B2}",
  mbfM: "\u{1D40C}",
  mbfMu: "\u{1D6B3}",
  mbfN: "\u{1D40D}",
  mbfNu: "\u{1D6B4}",
  mbfO: "\u{1D40E}",
  mbfOmega: "\u{1D6C0}",
  mbfOmicron: "\u{1D6B6}",
  mbfP: "\u{1D40F}",
  mbfPhi: "\u{1D6BD}",
  mbfPi: "\u{1D6B7}",
  mbfPsi: "\u{1D6BF}",
  mbfQ: "\u{1D410}",
  mbfR: "\u{1D411}",
  mbfRho: "\u{1D6B8}",
  mbfS: "\u{1D412}",
  mbfSigma: "\u{1D6BA}",
  mbfT: "\u{1D413}",
  mbfTau: "\u{1D6BB}",
  mbfTheta: "\u{1D6AF}",
  mbfU: "\u{1D414}",
  mbfUpsilon: "\u{1D6BC}",
  mbfV: "\u{1D415}",
  mbfW: "\u{1D416}",
  mbfX: "\u{1D417}",
  mbfXi: "\u{1D6B5}",
  mbfY: "\u{1D418}",
  mbfZ: "\u{1D419}",
  mbfZeta: "\u{1D6AD}",
  mbfa: "\u{1D41A}",
  mbfalpha: "\u{1D6C2}",
  mbfb: "\u{1D41B}",
  mbfbeta: "\u{1D6C3}",
  mbfc: "\u{1D41C}",
  mbfchi: "\u{1D6D8}",
  mbfd: "\u{1D41D}",
  mbfdelta: "\u{1D6C5}",
  mbfdigamma: "\u{1D7CB}",
  mbfe: "\u{1D41E}",
  mbfepsilon: "\u{1D6DC}",
  mbfeta: "\u{1D6C8}",
  mbff: "\u{1D41F}",
  mbffrakA: "\u{1D56C}",
  mbffrakB: "\u{1D56D}",
  mbffrakC: "\u{1D56E}",
  mbffrakD: "\u{1D56F}",
  mbffrakE: "\u{1D570}",
  mbffrakF: "\u{1D571}",
  mbffrakG: "\u{1D572}",
  mbffrakH: "\u{1D573}",
  mbffrakI: "\u{1D574}",
  mbffrakJ: "\u{1D575}",
  mbffrakK: "\u{1D576}",
  mbffrakL: "\u{1D577}",
  mbffrakM: "\u{1D578}",
  mbffrakN: "\u{1D579}",
  mbffrakO: "\u{1D57A}",
  mbffrakP: "\u{1D57B}",
  mbffrakQ: "\u{1D57C}",
  mbffrakR: "\u{1D57D}",
  mbffrakS: "\u{1D57E}",
  mbffrakT: "\u{1D57F}",
  mbffrakU: "\u{1D580}",
  mbffrakV: "\u{1D581}",
  mbffrakW: "\u{1D582}",
  mbffrakX: "\u{1D583}",
  mbffrakY: "\u{1D584}",
  mbffrakZ: "\u{1D585}",
  mbffraka: "\u{1D586}",
  mbffrakb: "\u{1D587}",
  mbffrakc: "\u{1D588}",
  mbffrakd: "\u{1D589}",
  mbffrake: "\u{1D58A}",
  mbffrakf: "\u{1D58B}",
  mbffrakg: "\u{1D58C}",
  mbffrakh: "\u{1D58D}",
  mbffraki: "\u{1D58E}",
  mbffrakj: "\u{1D58F}",
  mbffrakk: "\u{1D590}",
  mbffrakl: "\u{1D591}",
  mbffrakm: "\u{1D592}",
  mbffrakn: "\u{1D593}",
  mbffrako: "\u{1D594}",
  mbffrakp: "\u{1D595}",
  mbffrakq: "\u{1D596}",
  mbffrakr: "\u{1D597}",
  mbffraks: "\u{1D598}",
  mbffrakt: "\u{1D599}",
  mbffraku: "\u{1D59A}",
  mbffrakv: "\u{1D59B}",
  mbffrakw: "\u{1D59C}",
  mbffrakx: "\u{1D59D}",
  mbffraky: "\u{1D59E}",
  mbffrakz: "\u{1D59F}",
  mbfg: "\u{1D420}",
  mbfgamma: "\u{1D6C4}",
  mbfh: "\u{1D421}",
  mbfi: "\u{1D422}",
  mbfiota: "\u{1D6CA}",
  mbfitA: "\u{1D468}",
  mbfitAlpha: "\u{1D71C}",
  mbfitB: "\u{1D469}",
  mbfitBeta: "\u{1D71D}",
  mbfitC: "\u{1D46A}",
  mbfitChi: "\u{1D732}",
  mbfitD: "\u{1D46B}",
  mbfitDelta: "\u{1D71F}",
  mbfitE: "\u{1D46C}",
  mbfitEpsilon: "\u{1D720}",
  mbfitEta: "\u{1D722}",
  mbfitF: "\u{1D46D}",
  mbfitG: "\u{1D46E}",
  mbfitGamma: "\u{1D71E}",
  mbfitH: "\u{1D46F}",
  mbfitI: "\u{1D470}",
  mbfitIota: "\u{1D724}",
  mbfitJ: "\u{1D471}",
  mbfitK: "\u{1D472}",
  mbfitKappa: "\u{1D725}",
  mbfitL: "\u{1D473}",
  mbfitLambda: "\u{1D726}",
  mbfitM: "\u{1D474}",
  mbfitMu: "\u{1D727}",
  mbfitN: "\u{1D475}",
  mbfitNu: "\u{1D728}",
  mbfitO: "\u{1D476}",
  mbfitOmega: "\u{1D734}",
  mbfitOmicron: "\u{1D72A}",
  mbfitP: "\u{1D477}",
  mbfitPhi: "\u{1D731}",
  mbfitPi: "\u{1D72B}",
  mbfitPsi: "\u{1D733}",
  mbfitQ: "\u{1D478}",
  mbfitR: "\u{1D479}",
  mbfitRho: "\u{1D72C}",
  mbfitS: "\u{1D47A}",
  mbfitSigma: "\u{1D72E}",
  mbfitT: "\u{1D47B}",
  mbfitTau: "\u{1D72F}",
  mbfitTheta: "\u{1D723}",
  mbfitU: "\u{1D47C}",
  mbfitUpsilon: "\u{1D730}",
  mbfitV: "\u{1D47D}",
  mbfitW: "\u{1D47E}",
  mbfitX: "\u{1D47F}",
  mbfitXi: "\u{1D729}",
  mbfitY: "\u{1D480}",
  mbfitZ: "\u{1D481}",
  mbfitZeta: "\u{1D721}",
  mbfita: "\u{1D482}",
  mbfitalpha: "\u{1D736}",
  mbfitb: "\u{1D483}",
  mbfitbeta: "\u{1D737}",
  mbfitc: "\u{1D484}",
  mbfitchi: "\u{1D74C}",
  mbfitd: "\u{1D485}",
  mbfitdelta: "\u{1D739}",
  mbfite: "\u{1D486}",
  mbfitepsilon: "\u{1D750}",
  mbfiteta: "\u{1D73C}",
  mbfitf: "\u{1D487}",
  mbfitg: "\u{1D488}",
  mbfitgamma: "\u{1D738}",
  mbfith: "\u{1D489}",
  mbfiti: "\u{1D48A}",
  mbfitiota: "\u{1D73E}",
  mbfitj: "\u{1D48B}",
  mbfitk: "\u{1D48C}",
  mbfitkappa: "\u{1D73F}",
  mbfitl: "\u{1D48D}",
  mbfitlambda: "\u{1D740}",
  mbfitm: "\u{1D48E}",
  mbfitmu: "\u{1D741}",
  mbfitn: "\u{1D48F}",
  mbfitnabla: "\u{1D735}",
  mbfitnu: "\u{1D742}",
  mbfito: "\u{1D490}",
  mbfitomega: "\u{1D74E}",
  mbfitomicron: "\u{1D744}",
  mbfitp: "\u{1D491}",
  mbfitpartial: "\u{1D74F}",
  mbfitphi: "\u{1D753}",
  mbfitpi: "\u{1D745}",
  mbfitpsi: "\u{1D74D}",
  mbfitq: "\u{1D492}",
  mbfitr: "\u{1D493}",
  mbfitrho: "\u{1D746}",
  mbfits: "\u{1D494}",
  mbfitsansA: "\u{1D63C}",
  mbfitsansAlpha: "\u{1D790}",
  mbfitsansB: "\u{1D63D}",
  mbfitsansBeta: "\u{1D791}",
  mbfitsansC: "\u{1D63E}",
  mbfitsansChi: "\u{1D7A6}",
  mbfitsansD: "\u{1D63F}",
  mbfitsansDelta: "\u{1D793}",
  mbfitsansE: "\u{1D640}",
  mbfitsansEpsilon: "\u{1D794}",
  mbfitsansEta: "\u{1D796}",
  mbfitsansF: "\u{1D641}",
  mbfitsansG: "\u{1D642}",
  mbfitsansGamma: "\u{1D792}",
  mbfitsansH: "\u{1D643}",
  mbfitsansI: "\u{1D644}",
  mbfitsansIota: "\u{1D798}",
  mbfitsansJ: "\u{1D645}",
  mbfitsansK: "\u{1D646}",
  mbfitsansKappa: "\u{1D799}",
  mbfitsansL: "\u{1D647}",
  mbfitsansLambda: "\u{1D79A}",
  mbfitsansM: "\u{1D648}",
  mbfitsansMu: "\u{1D79B}",
  mbfitsansN: "\u{1D649}",
  mbfitsansNu: "\u{1D79C}",
  mbfitsansO: "\u{1D64A}",
  mbfitsansOmega: "\u{1D7A8}",
  mbfitsansOmicron: "\u{1D79E}",
  mbfitsansP: "\u{1D64B}",
  mbfitsansPhi: "\u{1D7A5}",
  mbfitsansPi: "\u{1D79F}",
  mbfitsansPsi: "\u{1D7A7}",
  mbfitsansQ: "\u{1D64C}",
  mbfitsansR: "\u{1D64D}",
  mbfitsansRho: "\u{1D7A0}",
  mbfitsansS: "\u{1D64E}",
  mbfitsansSigma: "\u{1D7A2}",
  mbfitsansT: "\u{1D64F}",
  mbfitsansTau: "\u{1D7A3}",
  mbfitsansTheta: "\u{1D797}",
  mbfitsansU: "\u{1D650}",
  mbfitsansUpsilon: "\u{1D7A4}",
  mbfitsansV: "\u{1D651}",
  mbfitsansW: "\u{1D652}",
  mbfitsansX: "\u{1D653}",
  mbfitsansXi: "\u{1D79D}",
  mbfitsansY: "\u{1D654}",
  mbfitsansZ: "\u{1D655}",
  mbfitsansZeta: "\u{1D795}",
  mbfitsansa: "\u{1D656}",
  mbfitsansalpha: "\u{1D7AA}",
  mbfitsansb: "\u{1D657}",
  mbfitsansbeta: "\u{1D7AB}",
  mbfitsansc: "\u{1D658}",
  mbfitsanschi: "\u{1D7C0}",
  mbfitsansd: "\u{1D659}",
  mbfitsansdelta: "\u{1D7AD}",
  mbfitsanse: "\u{1D65A}",
  mbfitsansepsilon: "\u{1D7C4}",
  mbfitsanseta: "\u{1D7B0}",
  mbfitsansf: "\u{1D65B}",
  mbfitsansg: "\u{1D65C}",
  mbfitsansgamma: "\u{1D7AC}",
  mbfitsansh: "\u{1D65D}",
  mbfitsansi: "\u{1D65E}",
  mbfitsansiota: "\u{1D7B2}",
  mbfitsansj: "\u{1D65F}",
  mbfitsansk: "\u{1D660}",
  mbfitsanskappa: "\u{1D7B3}",
  mbfitsansl: "\u{1D661}",
  mbfitsanslambda: "\u{1D7B4}",
  mbfitsansm: "\u{1D662}",
  mbfitsansmu: "\u{1D7B5}",
  mbfitsansn: "\u{1D663}",
  mbfitsansnabla: "\u{1D7A9}",
  mbfitsansnu: "\u{1D7B6}",
  mbfitsanso: "\u{1D664}",
  mbfitsansomega: "\u{1D7C2}",
  mbfitsansomicron: "\u{1D7B8}",
  mbfitsansp: "\u{1D665}",
  mbfitsanspartial: "\u{1D7C3}",
  mbfitsansphi: "\u{1D7C7}",
  mbfitsanspi: "\u{1D7B9}",
  mbfitsanspsi: "\u{1D7C1}",
  mbfitsansq: "\u{1D666}",
  mbfitsansr: "\u{1D667}",
  mbfitsansrho: "\u{1D7BA}",
  mbfitsanss: "\u{1D668}",
  mbfitsanssigma: "\u{1D7BC}",
  mbfitsanst: "\u{1D669}",
  mbfitsanstau: "\u{1D7BD}",
  mbfitsanstheta: "\u{1D7B1}",
  mbfitsansu: "\u{1D66A}",
  mbfitsansupsilon: "\u{1D7BE}",
  mbfitsansv: "\u{1D66B}",
  mbfitsansvarTheta: "\u{1D7A1}",
  mbfitsansvarepsilon: "\u{1D7AE}",
  mbfitsansvarkappa: "\u{1D7C6}",
  mbfitsansvarphi: "\u{1D7BF}",
  mbfitsansvarpi: "\u{1D7C9}",
  mbfitsansvarrho: "\u{1D7C8}",
  mbfitsansvarsigma: "\u{1D7BB}",
  mbfitsansvartheta: "\u{1D7C5}",
  mbfitsansw: "\u{1D66C}",
  mbfitsansx: "\u{1D66D}",
  mbfitsansxi: "\u{1D7B7}",
  mbfitsansy: "\u{1D66E}",
  mbfitsansz: "\u{1D66F}",
  mbfitsanszeta: "\u{1D7AF}",
  mbfitsigma: "\u{1D748}",
  mbfitt: "\u{1D495}",
  mbfittau: "\u{1D749}",
  mbfittheta: "\u{1D73D}",
  mbfitu: "\u{1D496}",
  mbfitupsilon: "\u{1D74A}",
  mbfitv: "\u{1D497}",
  mbfitvarTheta: "\u{1D72D}",
  mbfitvarepsilon: "\u{1D73A}",
  mbfitvarkappa: "\u{1D752}",
  mbfitvarphi: "\u{1D74B}",
  mbfitvarpi: "\u{1D755}",
  mbfitvarrho: "\u{1D754}",
  mbfitvarsigma: "\u{1D747}",
  mbfitvartheta: "\u{1D751}",
  mbfitw: "\u{1D498}",
  mbfitx: "\u{1D499}",
  mbfitxi: "\u{1D743}",
  mbfity: "\u{1D49A}",
  mbfitz: "\u{1D49B}",
  mbfitzeta: "\u{1D73B}",
  mbfj: "\u{1D423}",
  mbfk: "\u{1D424}",
  mbfkappa: "\u{1D6CB}",
  mbfl: "\u{1D425}",
  mbflambda: "\u{1D6CC}",
  mbfm: "\u{1D426}",
  mbfmu: "\u{1D6CD}",
  mbfn: "\u{1D427}",
  mbfnabla: "\u{1D6C1}",
  mbfnu: "\u{1D6CE}",
  mbfo: "\u{1D428}",
  mbfomega: "\u{1D6DA}",
  mbfomicron: "\u{1D6D0}",
  mbfp: "\u{1D429}",
  mbfpartial: "\u{1D6DB}",
  mbfphi: "\u{1D6DF}",
  mbfpi: "\u{1D6D1}",
  mbfpsi: "\u{1D6D9}",
  mbfq: "\u{1D42A}",
  mbfr: "\u{1D42B}",
  mbfrho: "\u{1D6D2}",
  mbfs: "\u{1D42C}",
  mbfsansA: "\u{1D5D4}",
  mbfsansAlpha: "\u{1D756}",
  mbfsansB: "\u{1D5D5}",
  mbfsansBeta: "\u{1D757}",
  mbfsansC: "\u{1D5D6}",
  mbfsansChi: "\u{1D76C}",
  mbfsansD: "\u{1D5D7}",
  mbfsansDelta: "\u{1D759}",
  mbfsansE: "\u{1D5D8}",
  mbfsansEpsilon: "\u{1D75A}",
  mbfsansEta: "\u{1D75C}",
  mbfsansF: "\u{1D5D9}",
  mbfsansG: "\u{1D5DA}",
  mbfsansGamma: "\u{1D758}",
  mbfsansH: "\u{1D5DB}",
  mbfsansI: "\u{1D5DC}",
  mbfsansIota: "\u{1D75E}",
  mbfsansJ: "\u{1D5DD}",
  mbfsansK: "\u{1D5DE}",
  mbfsansKappa: "\u{1D75F}",
  mbfsansL: "\u{1D5DF}",
  mbfsansLambda: "\u{1D760}",
  mbfsansM: "\u{1D5E0}",
  mbfsansMu: "\u{1D761}",
  mbfsansN: "\u{1D5E1}",
  mbfsansNu: "\u{1D762}",
  mbfsansO: "\u{1D5E2}",
  mbfsansOmega: "\u{1D76E}",
  mbfsansOmicron: "\u{1D764}",
  mbfsansP: "\u{1D5E3}",
  mbfsansPhi: "\u{1D76B}",
  mbfsansPi: "\u{1D765}",
  mbfsansPsi: "\u{1D76D}",
  mbfsansQ: "\u{1D5E4}",
  mbfsansR: "\u{1D5E5}",
  mbfsansRho: "\u{1D766}",
  mbfsansS: "\u{1D5E6}",
  mbfsansSigma: "\u{1D768}",
  mbfsansT: "\u{1D5E7}",
  mbfsansTau: "\u{1D769}",
  mbfsansTheta: "\u{1D75D}",
  mbfsansU: "\u{1D5E8}",
  mbfsansUpsilon: "\u{1D76A}",
  mbfsansV: "\u{1D5E9}",
  mbfsansW: "\u{1D5EA}",
  mbfsansX: "\u{1D5EB}",
  mbfsansXi: "\u{1D763}",
  mbfsansY: "\u{1D5EC}",
  mbfsansZ: "\u{1D5ED}",
  mbfsansZeta: "\u{1D75B}",
  mbfsansa: "\u{1D5EE}",
  mbfsansalpha: "\u{1D770}",
  mbfsansb: "\u{1D5EF}",
  mbfsansbeta: "\u{1D771}",
  mbfsansc: "\u{1D5F0}",
  mbfsanschi: "\u{1D786}",
  mbfsansd: "\u{1D5F1}",
  mbfsansdelta: "\u{1D773}",
  mbfsanse: "\u{1D5F2}",
  mbfsansepsilon: "\u{1D78A}",
  mbfsanseta: "\u{1D776}",
  mbfsansf: "\u{1D5F3}",
  mbfsansg: "\u{1D5F4}",
  mbfsansgamma: "\u{1D772}",
  mbfsansh: "\u{1D5F5}",
  mbfsansi: "\u{1D5F6}",
  mbfsansiota: "\u{1D778}",
  mbfsansj: "\u{1D5F7}",
  mbfsansk: "\u{1D5F8}",
  mbfsanskappa: "\u{1D779}",
  mbfsansl: "\u{1D5F9}",
  mbfsanslambda: "\u{1D77A}",
  mbfsansm: "\u{1D5FA}",
  mbfsansmu: "\u{1D77B}",
  mbfsansn: "\u{1D5FB}",
  mbfsansnabla: "\u{1D76F}",
  mbfsansnu: "\u{1D77C}",
  mbfsanso: "\u{1D5FC}",
  mbfsansomega: "\u{1D788}",
  mbfsansomicron: "\u{1D77E}",
  mbfsansp: "\u{1D5FD}",
  mbfsanspartial: "\u{1D789}",
  mbfsansphi: "\u{1D78D}",
  mbfsanspi: "\u{1D77F}",
  mbfsanspsi: "\u{1D787}",
  mbfsansq: "\u{1D5FE}",
  mbfsansr: "\u{1D5FF}",
  mbfsansrho: "\u{1D780}",
  mbfsanss: "\u{1D600}",
  mbfsanssigma: "\u{1D782}",
  mbfsanst: "\u{1D601}",
  mbfsanstau: "\u{1D783}",
  mbfsanstheta: "\u{1D777}",
  mbfsansu: "\u{1D602}",
  mbfsansupsilon: "\u{1D784}",
  mbfsansv: "\u{1D603}",
  mbfsansvarTheta: "\u{1D767}",
  mbfsansvarepsilon: "\u{1D774}",
  mbfsansvarkappa: "\u{1D78C}",
  mbfsansvarphi: "\u{1D785}",
  mbfsansvarpi: "\u{1D78F}",
  mbfsansvarrho: "\u{1D78E}",
  mbfsansvarsigma: "\u{1D781}",
  mbfsansvartheta: "\u{1D78B}",
  mbfsansw: "\u{1D604}",
  mbfsansx: "\u{1D605}",
  mbfsansxi: "\u{1D77D}",
  mbfsansy: "\u{1D606}",
  mbfsansz: "\u{1D607}",
  mbfsanszeta: "\u{1D775}",
  mbfscrA: "\u{1D4D0}",
  mbfscrB: "\u{1D4D1}",
  mbfscrC: "\u{1D4D2}",
  mbfscrD: "\u{1D4D3}",
  mbfscrE: "\u{1D4D4}",
  mbfscrF: "\u{1D4D5}",
  mbfscrG: "\u{1D4D6}",
  mbfscrH: "\u{1D4D7}",
  mbfscrI: "\u{1D4D8}",
  mbfscrJ: "\u{1D4D9}",
  mbfscrK: "\u{1D4DA}",
  mbfscrL: "\u{1D4DB}",
  mbfscrM: "\u{1D4DC}",
  mbfscrN: "\u{1D4DD}",
  mbfscrO: "\u{1D4DE}",
  mbfscrP: "\u{1D4DF}",
  mbfscrQ: "\u{1D4E0}",
  mbfscrR: "\u{1D4E1}",
  mbfscrS: "\u{1D4E2}",
  mbfscrT: "\u{1D4E3}",
  mbfscrU: "\u{1D4E4}",
  mbfscrV: "\u{1D4E5}",
  mbfscrW: "\u{1D4E6}",
  mbfscrX: "\u{1D4E7}",
  mbfscrY: "\u{1D4E8}",
  mbfscrZ: "\u{1D4E9}",
  mbfscra: "\u{1D4EA}",
  mbfscrb: "\u{1D4EB}",
  mbfscrc: "\u{1D4EC}",
  mbfscrd: "\u{1D4ED}",
  mbfscre: "\u{1D4EE}",
  mbfscrf: "\u{1D4EF}",
  mbfscrg: "\u{1D4F0}",
  mbfscrh: "\u{1D4F1}",
  mbfscri: "\u{1D4F2}",
  mbfscrj: "\u{1D4F3}",
  mbfscrk: "\u{1D4F4}",
  mbfscrl: "\u{1D4F5}",
  mbfscrm: "\u{1D4F6}",
  mbfscrn: "\u{1D4F7}",
  mbfscro: "\u{1D4F8}",
  mbfscrp: "\u{1D4F9}",
  mbfscrq: "\u{1D4FA}",
  mbfscrr: "\u{1D4FB}",
  mbfscrs: "\u{1D4FC}",
  mbfscrt: "\u{1D4FD}",
  mbfscru: "\u{1D4FE}",
  mbfscrv: "\u{1D4FF}",
  mbfscrw: "\u{1D500}",
  mbfscrx: "\u{1D501}",
  mbfscry: "\u{1D502}",
  mbfscrz: "\u{1D503}",
  mbfsigma: "\u{1D6D4}",
  mbft: "\u{1D42D}",
  mbftau: "\u{1D6D5}",
  mbftheta: "\u{1D6C9}",
  mbfu: "\u{1D42E}",
  mbfupsilon: "\u{1D6D6}",
  mbfv: "\u{1D42F}",
  mbfvarTheta: "\u{1D6B9}",
  mbfvarepsilon: "\u{1D6C6}",
  mbfvarkappa: "\u{1D6DE}",
  mbfvarphi: "\u{1D6D7}",
  mbfvarpi: "\u{1D6E1}",
  mbfvarrho: "\u{1D6E0}",
  mbfvarsigma: "\u{1D6D3}",
  mbfvartheta: "\u{1D6DD}",
  mbfw: "\u{1D430}",
  mbfx: "\u{1D431}",
  mbfxi: "\u{1D6CF}",
  mbfy: "\u{1D432}",
  mbfz: "\u{1D433}",
  mbfzeta: "\u{1D6C7}",
  mfrakA: "\u{1D504}",
  mfrakB: "\u{1D505}",
  mfrakC: "\u{212D}",
  mfrakD: "\u{1D507}",
  mfrakE: "\u{1D508}",
  mfrakF: "\u{1D509}",
  mfrakG: "\u{1D50A}",
  mfrakH: "\u{210C}",
  mfrakJ: "\u{1D50D}",
  mfrakK: "\u{1D50E}",
  mfrakL: "\u{1D50F}",
  mfrakM: "\u{1D510}",
  mfrakN: "\u{1D511}",
  mfrakO: "\u{1D512}",
  mfrakP: "\u{1D513}",
  mfrakQ: "\u{1D514}",
  mfrakS: "\u{1D516}",
  mfrakT: "\u{1D517}",
  mfrakU: "\u{1D518}",
  mfrakV: "\u{1D519}",
  mfrakW: "\u{1D51A}",
  mfrakX: "\u{1D51B}",
  mfrakY: "\u{1D51C}",
  mfrakZ: "\u{2128}",
  mfraka: "\u{1D51E}",
  mfrakb: "\u{1D51F}",
  mfrakc: "\u{1D520}",
  mfrakd: "\u{1D521}",
  mfrake: "\u{1D522}",
  mfrakf: "\u{1D523}",
  mfrakg: "\u{1D524}",
  mfrakh: "\u{1D525}",
  mfraki: "\u{1D526}",
  mfrakj: "\u{1D527}",
  mfrakk: "\u{1D528}",
  mfrakl: "\u{1D529}",
  mfrakm: "\u{1D52A}",
  mfrakn: "\u{1D52B}",
  mfrako: "\u{1D52C}",
  mfrakp: "\u{1D52D}",
  mfrakq: "\u{1D52E}",
  mfrakr: "\u{1D52F}",
  mfraks: "\u{1D530}",
  mfrakt: "\u{1D531}",
  mfraku: "\u{1D532}",
  mfrakv: "\u{1D533}",
  mfrakw: "\u{1D534}",
  mfrakx: "\u{1D535}",
  mfraky: "\u{1D536}",
  mfrakz: "\u{1D537}",
  mitA: "\u{1D434}",
  mitAlpha: "\u{1D6E2}",
  mitB: "\u{1D435}",
  mitBeta: "\u{1D6E3}",
  mitC: "\u{1D436}",
  mitChi: "\u{1D6F8}",
  mitD: "\u{1D437}",
  mitDelta: "\u{1D6E5}",
  mitE: "\u{1D438}",
  mitEpsilon: "\u{1D6E6}",
  mitEta: "\u{1D6E8}",
  mitF: "\u{1D439}",
  mitG: "\u{1D43A}",
  mitGamma: "\u{1D6E4}",
  mitH: "\u{1D43B}",
  mitI: "\u{1D43C}",
  mitIota: "\u{1D6EA}",
  mitJ: "\u{1D43D}",
  mitK: "\u{1D43E}",
  mitKappa: "\u{1D6EB}",
  mitL: "\u{1D43F}",
  mitLambda: "\u{1D6EC}",
  mitM: "\u{1D440}",
  mitMu: "\u{1D6ED}",
  mitN: "\u{1D441}",
  mitNu: "\u{1D6EE}",
  mitO: "\u{1D442}",
  mitOmega: "\u{1D6FA}",
  mitOmicron: "\u{1D6F0}",
  mitP: "\u{1D443}",
  mitPhi: "\u{1D6F7}",
  mitPi: "\u{1D6F1}",
  mitPsi: "\u{1D6F9}",
  mitQ: "\u{1D444}",
  mitR: "\u{1D445}",
  mitRho: "\u{1D6F2}",
  mitS: "\u{1D446}",
  mitSigma: "\u{1D6F4}",
  mitT: "\u{1D447}",
  mitTau: "\u{1D6F5}",
  mitTheta: "\u{1D6E9}",
  mitU: "\u{1D448}",
  mitUpsilon: "\u{1D6F6}",
  mitV: "\u{1D449}",
  mitW: "\u{1D44A}",
  mitX: "\u{1D44B}",
  mitXi: "\u{1D6EF}",
  mitY: "\u{1D44C}",
  mitZ: "\u{1D44D}",
  mitZeta: "\u{1D6E7}",
  mita: "\u{1D44E}",
  mitalpha: "\u{1D6FC}",
  mitb: "\u{1D44F}",
  mitbeta: "\u{1D6FD}",
  mitc: "\u{1D450}",
  mitchi: "\u{1D712}",
  mitd: "\u{1D451}",
  mitdelta: "\u{1D6FF}",
  mite: "\u{1D452}",
  mitepsilon: "\u{1D716}",
  miteta: "\u{1D702}",
  mitf: "\u{1D453}",
  mitg: "\u{1D454}",
  mitgamma: "\u{1D6FE}",
  miti: "\u{1D456}",
  mitiota: "\u{1D704}",
  mitj: "\u{1D457}",
  mitk: "\u{1D458}",
  mitkappa: "\u{1D705}",
  mitl: "\u{1D459}",
  mitlambda: "\u{1D706}",
  mitm: "\u{1D45A}",
  mitmu: "\u{1D707}",
  mitn: "\u{1D45B}",
  mitnabla: "\u{1D6FB}",
  mitnu: "\u{1D708}",
  mito: "\u{1D45C}",
  mitomega: "\u{1D714}",
  mitomicron: "\u{1D70A}",
  mitp: "\u{1D45D}",
  mitpartial: "\u{1D715}",
  mitphi: "\u{1D719}",
  mitpi: "\u{1D70B}",
  mitpsi: "\u{1D713}",
  mitq: "\u{1D45E}",
  mitr: "\u{1D45F}",
  mitrho: "\u{1D70C}",
  mits: "\u{1D460}",
  mitsansA: "\u{1D608}",
  mitsansB: "\u{1D609}",
  mitsansC: "\u{1D60A}",
  mitsansD: "\u{1D60B}",
  mitsansE: "\u{1D60C}",
  mitsansF: "\u{1D60D}",
  mitsansG: "\u{1D60E}",
  mitsansH: "\u{1D60F}",
  mitsansI: "\u{1D610}",
  mitsansJ: "\u{1D611}",
  mitsansK: "\u{1D612}",
  mitsansL: "\u{1D613}",
  mitsansM: "\u{1D614}",
  mitsansN: "\u{1D615}",
  mitsansO: "\u{1D616}",
  mitsansP: "\u{1D617}",
  mitsansQ: "\u{1D618}",
  mitsansR: "\u{1D619}",
  mitsansS: "\u{1D61A}",
  mitsansT: "\u{1D61B}",
  mitsansU: "\u{1D61C}",
  mitsansV: "\u{1D61D}",
  mitsansW: "\u{1D61E}",
  mitsansX: "\u{1D61F}",
  mitsansY: "\u{1D620}",
  mitsansZ: "\u{1D621}",
  mitsansa: "\u{1D622}",
  mitsansb: "\u{1D623}",
  mitsansc: "\u{1D624}",
  mitsansd: "\u{1D625}",
  mitsanse: "\u{1D626}",
  mitsansf: "\u{1D627}",
  mitsansg: "\u{1D628}",
  mitsansh: "\u{1D629}",
  mitsansi: "\u{1D62A}",
  mitsansj: "\u{1D62B}",
  mitsansk: "\u{1D62C}",
  mitsansl: "\u{1D62D}",
  mitsansm: "\u{1D62E}",
  mitsansn: "\u{1D62F}",
  mitsanso: "\u{1D630}",
  mitsansp: "\u{1D631}",
  mitsansq: "\u{1D632}",
  mitsansr: "\u{1D633}",
  mitsanss: "\u{1D634}",
  mitsanst: "\u{1D635}",
  mitsansu: "\u{1D636}",
  mitsansv: "\u{1D637}",
  mitsansw: "\u{1D638}",
  mitsansx: "\u{1D639}",
  mitsansy: "\u{1D63A}",
  mitsansz: "\u{1D63B}",
  mitsigma: "\u{1D70E}",
  mitt: "\u{1D461}",
  mittau: "\u{1D70F}",
  mittheta: "\u{1D703}",
  mitu: "\u{1D462}",
  mitupsilon: "\u{1D710}",
  mitv: "\u{1D463}",
  mitvarTheta: "\u{1D6F3}",
  mitvarepsilon: "\u{1D700}",
  mitvarkappa: "\u{1D718}",
  mitvarphi: "\u{1D711}",
  mitvarpi: "\u{1D71B}",
  mitvarrho: "\u{1D71A}",
  mitvarsigma: "\u{1D70D}",
  mitvartheta: "\u{1D717}",
  mitw: "\u{1D464}",
  mitx: "\u{1D465}",
  mitxi: "\u{1D709}",
  mity: "\u{1D466}",
  mitz: "\u{1D467}",
  mitzeta: "\u{1D701}",
  msansA: "\u{1D5A0}",
  msansB: "\u{1D5A1}",
  msansC: "\u{1D5A2}",
  msansD: "\u{1D5A3}",
  msansE: "\u{1D5A4}",
  msansF: "\u{1D5A5}",
  msansG: "\u{1D5A6}",
  msansH: "\u{1D5A7}",
  msansI: "\u{1D5A8}",
  msansJ: "\u{1D5A9}",
  msansK: "\u{1D5AA}",
  msansL: "\u{1D5AB}",
  msansM: "\u{1D5AC}",
  msansN: "\u{1D5AD}",
  msansO: "\u{1D5AE}",
  msansP: "\u{1D5AF}",
  msansQ: "\u{1D5B0}",
  msansR: "\u{1D5B1}",
  msansS: "\u{1D5B2}",
  msansT: "\u{1D5B3}",
  msansU: "\u{1D5B4}",
  msansV: "\u{1D5B5}",
  msansW: "\u{1D5B6}",
  msansX: "\u{1D5B7}",
  msansY: "\u{1D5B8}",
  msansZ: "\u{1D5B9}",
  msansa: "\u{1D5BA}",
  msansb: "\u{1D5BB}",
  msansc: "\u{1D5BC}",
  msansd: "\u{1D5BD}",
  msanse: "\u{1D5BE}",
  msansf: "\u{1D5BF}",
  msansg: "\u{1D5C0}",
  msansh: "\u{1D5C1}",
  msansi: "\u{1D5C2}",
  msansj: "\u{1D5C3}",
  msansk: "\u{1D5C4}",
  msansl: "\u{1D5C5}",
  msansm: "\u{1D5C6}",
  msansn: "\u{1D5C7}",
  msanso: "\u{1D5C8}",
  msansp: "\u{1D5C9}",
  msansq: "\u{1D5CA}",
  msansr: "\u{1D5CB}",
  msanss: "\u{1D5CC}",
  msanst: "\u{1D5CD}",
  msansu: "\u{1D5CE}",
  msansv: "\u{1D5CF}",
  msansw: "\u{1D5D0}",
  msansx: "\u{1D5D1}",
  msansy: "\u{1D5D2}",
  msansz: "\u{1D5D3}",
  mscrA: "\u{1D49C}",
  mscrB: "\u{212C}",
  mscrC: "\u{1D49E}",
  mscrD: "\u{1D49F}",
  mscrE: "\u{2130}",
  mscrF: "\u{2131}",
  mscrG: "\u{1D4A2}",
  mscrH: "\u{210B}",
  mscrI: "\u{2110}",
  mscrJ: "\u{1D4A5}",
  mscrK: "\u{1D4A6}",
  mscrL: "\u{2112}",
  mscrM: "\u{2133}",
  mscrN: "\u{1D4A9}",
  mscrO: "\u{1D4AA}",
  mscrP: "\u{1D4AB}",
  mscrQ: "\u{1D4AC}",
  mscrR: "\u{211B}",
  mscrS: "\u{1D4AE}",
  mscrT: "\u{1D4AF}",
  mscrU: "\u{1D4B0}",
  mscrV: "\u{1D4B1}",
  mscrW: "\u{1D4B2}",
  mscrX: "\u{1D4B3}",
  mscrY: "\u{1D4B4}",
  mscrZ: "\u{1D4B5}",
  mscra: "\u{1D4B6}",
  mscrb: "\u{1D4B7}",
  mscrc: "\u{1D4B8}",
  mscrd: "\u{1D4B9}",
  mscre: "\u{212F}",
  mscrf: "\u{1D4BB}",
  mscrg: "\u{210A}",
  mscrh: "\u{1D4BD}",
  mscri: "\u{1D4BE}",
  mscrj: "\u{1D4BF}",
  mscrk: "\u{1D4C0}",
  mscrl: "\u{1D4C1}",
  mscrm: "\u{1D4C2}",
  mscrn: "\u{1D4C3}",
  mscro: "\u{2134}",
  mscrp: "\u{1D4C5}",
  mscrq: "\u{1D4C6}",
  mscrr: "\u{1D4C7}",
  mscrs: "\u{1D4C8}",
  mscrt: "\u{1D4C9}",
  mscru: "\u{1D4CA}",
  mscrv: "\u{1D4CB}",
  mscrw: "\u{1D4CC}",
  mscrx: "\u{1D4CD}",
  mscry: "\u{1D4CE}",
  mscrz: "\u{1D4CF}",
  mttA: "\u{1D670}",
  mttB: "\u{1D671}",
  mttC: "\u{1D672}",
  mttD: "\u{1D673}",
  mttE: "\u{1D674}",
  mttF: "\u{1D675}",
  mttG: "\u{1D676}",
  mttH: "\u{1D677}",
  mttI: "\u{1D678}",
  mttJ: "\u{1D679}",
  mttK: "\u{1D67A}",
  mttL: "\u{1D67B}",
  mttM: "\u{1D67C}",
  mttN: "\u{1D67D}",
  mttO: "\u{1D67E}",
  mttP: "\u{1D67F}",
  mttQ: "\u{1D680}",
  mttR: "\u{1D681}",
  mttS: "\u{1D682}",
  mttT: "\u{1D683}",
  mttU: "\u{1D684}",
  mttV: "\u{1D685}",
  mttW: "\u{1D686}",
  mttX: "\u{1D687}",
  mttY: "\u{1D688}",
  mttZ: "\u{1D689}",
  mtta: "\u{1D68A}",
  mttb: "\u{1D68B}",
  mttc: "\u{1D68C}",
  mttd: "\u{1D68D}",
  mtte: "\u{1D68E}",
  mttf: "\u{1D68F}",
  mttg: "\u{1D690}",
  mtth: "\u{1D691}",
  mtti: "\u{1D692}",
  mttj: "\u{1D693}",
  mttk: "\u{1D694}",
  mttl: "\u{1D695}",
  mttm: "\u{1D696}",
  mttn: "\u{1D697}",
  mtto: "\u{1D698}",
  mttp: "\u{1D699}",
  mttq: "\u{1D69A}",
  mttr: "\u{1D69B}",
  mtts: "\u{1D69C}",
  mttt: "\u{1D69D}",
  mttu: "\u{1D69E}",
  mttv: "\u{1D69F}",
  mttw: "\u{1D6A0}",
  mttx: "\u{1D6A1}",
  mtty: "\u{1D6A2}",
  mttz: "\u{1D6A3}",
  mupAlpha: "\u{0391}",
  mupBeta: "\u{0392}",
  mupChi: "\u{03A7}",
  mupDelta: "\u{0394}",
  mupEpsilon: "\u{0395}",
  mupEta: "\u{0397}",
  mupGamma: "\u{0393}",
  mupIota: "\u{0399}",
  mupKappa: "\u{039A}",
  mupLambda: "\u{039B}",
  mupMu: "\u{039C}",
  mupNu: "\u{039D}",
  mupOmega: "\u{03A9}",
  mupOmicron: "\u{039F}",
  mupPhi: "\u{03A6}",
  mupPi: "\u{03A0}",
  mupPsi: "\u{03A8}",
  mupRho: "\u{03A1}",
  mupSigma: "\u{03A3}",
  mupTau: "\u{03A4}",
  mupTheta: "\u{0398}",
  mupUpsilon: "\u{03A5}",
  mupXi: "\u{039E}",
  mupZeta: "\u{0396}",
  mupalpha: "\u{03B1}",
  mupbeta: "\u{03B2}",
  mupchi: "\u{03C7}",
  mupdelta: "\u{03B4}",
  mupepsilon: "\u{03F5}",
  mupeta: "\u{03B7}",
  mupgamma: "\u{03B3}",
  mupiota: "\u{03B9}",
  mupkappa: "\u{03BA}",
  muplambda: "\u{03BB}",
  mupmu: "\u{03BC}",
  mupnu: "\u{03BD}",
  mupomega: "\u{03C9}",
  mupomicron: "\u{03BF}",
  mupphi: "\u{03D5}",
  muppi: "\u{03C0}",
  muppsi: "\u{03C8}",
  muprho: "\u{03C1}",
  mupsigma: "\u{03C3}",
  muptau: "\u{03C4}",
  muptheta: "\u{03B8}",
  mupupsilon: "\u{03C5}",
  mupvarTheta: "\u{03F4}",
  mupvarepsilon: "\u{03B5}",
  mupvarkappa: "\u{03F0}",
  mupvarphi: "\u{03C6}",
  mupvarpi: "\u{03D6}",
  mupvarrho: "\u{03F1}",
  mupvarsigma: "\u{03C2}",
  mupvartheta: "\u{03D1}",
  mupxi: "\u{03BE}",
  mupzeta: "\u{03B6}",
  // NOTE disabled to re-use MathJax's definition (['\u2207', {mathvariant: TexConstant.Variant.NORMAL}])
  // nabla: '\u{2207}',
  partial: "\u{2202}",
  turnediota: "\u{2129}",
  upDigamma: "\u{03DC}",
  updigamma: "\u{03DD}",
  wp: "\u{2118}",
  // \mathord
  APLboxquestion: "\u{2370}",
  APLboxupcaret: "\u{2353}",
  APLnotbackslash: "\u{2340}",
  Bbbeight: "\u{1D7E0}",
  Bbbfive: "\u{1D7DD}",
  Bbbfour: "\u{1D7DC}",
  Bbbnine: "\u{1D7E1}",
  Bbbone: "\u{1D7D9}",
  Bbbpi: "\u{213C}",
  Bbbseven: "\u{1D7DF}",
  Bbbsix: "\u{1D7DE}",
  Bbbthree: "\u{1D7DB}",
  Bbbtwo: "\u{1D7DA}",
  Bbbzero: "\u{1D7D8}",
  Eulerconst: "\u{2107}",
  Exclam: "\u{203C}",
  Finv: "\u{2132}",
  Game: "\u{2141}",
  Hermaphrodite: "\u{26A5}",
  Planckconst: "\u{210E}",
  PropertyLine: "\u{214A}",
  QED: "\u{220E}",
  Question: "\u{2047}",
  Yup: "\u{2144}",
  Zbar: "\u{01B5}",
  accurrent: "\u{23E6}",
  acidfree: "\u{267E}",
  acwopencirclearrow: "\u{21BA}",
  angdnr: "\u{299F}",
  angle: "\u{2220}",
  angles: "\u{299E}",
  angleubar: "\u{29A4}",
  astrosun: "\u{2609}",
  backdprime: "\u{2036}",
  backprime: "\u{2035}",
  // NOTE disabled to fallback to core MathJax which uses u2216
  // backslash: '\u{005C}',
  backtrprime: "\u{2037}",
  barleftarrowrightarrowbar: "\u{21B9}",
  barovernorthwestarrow: "\u{21B8}",
  bbrktbrk: "\u{23B6}",
  bdtriplevdash: "\u{2506}",
  because: "\u{2235}",
  benzenr: "\u{23E3}",
  bigblacktriangledown: "\u{25BC}",
  bigblacktriangleup: "\u{25B2}",
  bigstar: "\u{2605}",
  bigtriangledown: "\u{25BD}",
  bigwhitestar: "\u{2606}",
  blackcircledownarrow: "\u{29ED}",
  blackcircledrightdot: "\u{2688}",
  blackcircledtwodots: "\u{2689}",
  blackcircleulquadwhite: "\u{25D5}",
  blackdiamonddownarrow: "\u{29EA}",
  blackinwhitediamond: "\u{25C8}",
  blackinwhitesquare: "\u{25A3}",
  blacklefthalfcircle: "\u{25D6}",
  blackpointerleft: "\u{25C4}",
  blackpointerright: "\u{25BA}",
  blackrighthalfcircle: "\u{25D7}",
  blacksmiley: "\u{263B}",
  blacktriangle: "\u{25B4}",
  blacktriangledown: "\u{25BE}",
  blacktriangleleft: "\u{25C0}",
  blacktriangleright: "\u{25B6}",
  blanksymbol: "\u{2422}",
  blkhorzoval: "\u{2B2C}",
  blkvertoval: "\u{2B2E}",
  blockfull: "\u{2588}",
  blockhalfshaded: "\u{2592}",
  blocklefthalf: "\u{258C}",
  blocklowhalf: "\u{2584}",
  blockqtrshaded: "\u{2591}",
  blockrighthalf: "\u{2590}",
  blockthreeqtrshaded: "\u{2593}",
  blockuphalf: "\u{2580}",
  bot: "\u{22A5}",
  botsemicircle: "\u{25E1}",
  boxonbox: "\u{29C9}",
  bullseye: "\u{25CE}",
  caretinsert: "\u{2038}",
  carriagereturn: "\u{21B5}",
  checkmark: "\u{2713}",
  cirE: "\u{29C3}",
  circlebottomhalfblack: "\u{25D2}",
  circledbullet: "\u{29BF}",
  circledownarrow: "\u{29EC}",
  circledrightdot: "\u{2686}",
  circledstar: "\u{272A}",
  circledtwodots: "\u{2687}",
  circledwhitebullet: "\u{29BE}",
  circlelefthalfblack: "\u{25D0}",
  circlellquad: "\u{25F5}",
  circlelrquad: "\u{25F6}",
  circlerighthalfblack: "\u{25D1}",
  circletophalfblack: "\u{25D3}",
  circleulquad: "\u{25F4}",
  circleurquad: "\u{25F7}",
  circleurquadblack: "\u{25D4}",
  circlevertfill: "\u{25CD}",
  cirscir: "\u{29C2}",
  clubsuit: "\u{2663}",
  complement: "\u{2201}",
  conictaper: "\u{2332}",
  cwopencirclearrow: "\u{21BB}",
  danger: "\u{2621}",
  diameter: "\u{2300}",
  diamondbotblack: "\u{2B19}",
  diamondcdot: "\u{27D0}",
  diamondleftblack: "\u{2B16}",
  diamondrightblack: "\u{2B17}",
  diamondsuit: "\u{2662}",
  diamondtopblack: "\u{2B18}",
  dicei: "\u{2680}",
  diceii: "\u{2681}",
  diceiii: "\u{2682}",
  diceiv: "\u{2683}",
  dicev: "\u{2684}",
  dicevi: "\u{2685}",
  dingasterisk: "\u{273D}",
  dottedcircle: "\u{25CC}",
  dottedsquare: "\u{2B1A}",
  downdasharrow: "\u{21E3}",
  downrightcurvedarrow: "\u{2935}",
  downtriangleleftblack: "\u{29E8}",
  downtrianglerightblack: "\u{29E9}",
  downwhitearrow: "\u{21E9}",
  dprime: "\u{2033}",
  draftingarrow: "\u{279B}",
  eighthnote: "\u{266A}",
  elinters: "\u{23E7}",
  // NOTE STIX TWO fonts have "circle-slash" as normal form of u2205 (cf. varnothing) and zero-slash as variant of u2205; CM has the reverse.
  emptyset: ["\u2205", { variantForm: true }],
  emptysetoarr: "\u{29B3}",
  emptysetoarrl: "\u{29B4}",
  emptysetobar: "\u{29B1}",
  emptysetocirc: "\u{29B2}",
  enclosecircle: "\u{20DD}",
  enclosediamond: "\u{20DF}",
  enclosesquare: "\u{20DE}",
  enclosetriangle: "\u{20E4}",
  enleadertwodots: "\u{2025}",
  errbarblackcircle: "\u{29F3}",
  errbarblackdiamond: "\u{29F1}",
  errbarblacksquare: "\u{29EF}",
  errbarcircle: "\u{29F2}",
  errbardiamond: "\u{29F0}",
  errbarsquare: "\u{29EE}",
  euro: "\u{20AC}",
  exists: "\u{2203}",
  fdiagovnearrow: "\u{292F}",
  fdiagovrdiag: "\u{292C}",
  female: "\u{2640}",
  fisheye: "\u{25C9}",
  flat: "\u{266D}",
  fltns: "\u{23E5}",
  forall: "\u{2200}",
  fourvdots: "\u{2999}",
  gtlpar: "\u{29A0}",
  harrowextender: "\u{23AF}",
  heartsuit: "\u{2661}",
  hermitmatrix: "\u{22B9}",
  hexagon: "\u{2394}",
  hexagonblack: "\u{2B23}",
  horizbar: "\u{2015}",
  house: "\u{2302}",
  hrectangle: "\u{25AD}",
  hrectangleblack: "\u{25AC}",
  hyphenbullet: "\u{2043}",
  hzigzag: "\u{3030}",
  iinfin: "\u{29DC}",
  increment: "\u{2206}",
  infty: "\u{221E}",
  intbottom: "\u{2321}",
  intextender: "\u{23AE}",
  inttop: "\u{2320}",
  inversebullet: "\u{25D8}",
  inversewhitecircle: "\u{25D9}",
  invnot: "\u{2310}",
  invwhitelowerhalfcircle: "\u{25DB}",
  invwhiteupperhalfcircle: "\u{25DA}",
  laplac: "\u{29E0}",
  lbracelend: "\u{23A9}",
  lbracemid: "\u{23A8}",
  lbraceuend: "\u{23A7}",
  lbrackextender: "\u{23A2}",
  lbracklend: "\u{23A3}",
  lbrackuend: "\u{23A1}",
  leftdasharrow: "\u{21E0}",
  leftmoon: "\u{263E}",
  leftwhitearrow: "\u{21E6}",
  lgblkcircle: "\u{2B24}",
  lgblksquare: "\u{2B1B}",
  lgwhtcircle: "\u{25EF}",
  lgwhtsquare: "\u{2B1C}",
  linefeed: "\u{21B4}",
  llarc: "\u{25DF}",
  llblacktriangle: "\u{25E3}",
  lltriangle: "\u{25FA}",
  lparenextender: "\u{239C}",
  lparenlend: "\u{239D}",
  lparenuend: "\u{239B}",
  lrarc: "\u{25DE}",
  lrblacktriangle: "\u{25E2}",
  lrtriangle: "\u{25FF}",
  lvboxline: "\u{23B8}",
  male: "\u{2642}",
  maltese: "\u{2720}",
  mathampersand: "\u{0026}",
  mathatsign: "\u{0040}",
  mathdollar: "\u{0024}",
  mathoctothorpe: "\u{0023}",
  mathparagraph: "\u{00B6}",
  mathpercent: "\u{0025}",
  mathperiod: "\u{002E}",
  mathquestion: "\u{003F}",
  mathsection: "\u{00A7}",
  mathslash: "\u{002F}",
  mathsterling: "\u{00A3}",
  mathvisiblespace: "\u{2423}",
  mathyen: "\u{00A5}",
  mbfeight: "\u{1D7D6}",
  mbffive: "\u{1D7D3}",
  mbffour: "\u{1D7D2}",
  mbfnine: "\u{1D7D7}",
  mbfone: "\u{1D7CF}",
  mbfsanseight: "\u{1D7F4}",
  mbfsansfive: "\u{1D7F1}",
  mbfsansfour: "\u{1D7F0}",
  mbfsansnine: "\u{1D7F5}",
  mbfsansone: "\u{1D7ED}",
  mbfsansseven: "\u{1D7F3}",
  mbfsanssix: "\u{1D7F2}",
  mbfsansthree: "\u{1D7EF}",
  mbfsanstwo: "\u{1D7EE}",
  mbfsanszero: "\u{1D7EC}",
  mbfseven: "\u{1D7D5}",
  mbfsix: "\u{1D7D4}",
  mbfthree: "\u{1D7D1}",
  mbftwo: "\u{1D7D0}",
  mbfzero: "\u{1D7CE}",
  mdblkcircle: "\u{26AB}",
  mdblkdiamond: "\u{2B25}",
  mdblklozenge: "\u{2B27}",
  mdblksquare: "\u{25FC}",
  mdlgblkcircle: "\u{25CF}",
  mdlgblkdiamond: "\u{25C6}",
  mdlgblksquare: "\u{25A0}",
  mdlgwhtdiamond: "\u{25C7}",
  mdlgwhtlozenge: "\u{25CA}",
  mdlgwhtsquare: "\u{25A1}",
  mdsmblkcircle: "\u{2981}",
  mdsmblksquare: "\u{25FE}",
  mdsmwhtcircle: "\u{26AC}",
  mdsmwhtsquare: "\u{25FD}",
  mdwhtcircle: "\u{26AA}",
  mdwhtdiamond: "\u{2B26}",
  mdwhtlozenge: "\u{2B28}",
  mdwhtsquare: "\u{25FB}",
  measangledltosw: "\u{29AF}",
  measangledrtose: "\u{29AE}",
  measangleldtosw: "\u{29AB}",
  measanglelutonw: "\u{29A9}",
  measanglerdtose: "\u{29AA}",
  measanglerutone: "\u{29A8}",
  measangleultonw: "\u{29AD}",
  measangleurtone: "\u{29AC}",
  measuredangle: "\u{2221}",
  measuredangleleft: "\u{299B}",
  measuredrightangle: "\u{22BE}",
  medblackstar: "\u{2B51}",
  medwhitestar: "\u{2B50}",
  mho: "\u{2127}",
  mitBbbD: "\u{2145}",
  mitBbbd: "\u{2146}",
  mitBbbe: "\u{2147}",
  mitBbbi: "\u{2148}",
  mitBbbj: "\u{2149}",
  msanseight: "\u{1D7EA}",
  msansfive: "\u{1D7E7}",
  msansfour: "\u{1D7E6}",
  msansnine: "\u{1D7EB}",
  msansone: "\u{1D7E3}",
  msansseven: "\u{1D7E9}",
  msanssix: "\u{1D7E8}",
  msansthree: "\u{1D7E5}",
  msanstwo: "\u{1D7E4}",
  msanszero: "\u{1D7E2}",
  mtteight: "\u{1D7FE}",
  mttfive: "\u{1D7FB}",
  mttfour: "\u{1D7FA}",
  mttnine: "\u{1D7FF}",
  mttone: "\u{1D7F7}",
  mttseven: "\u{1D7FD}",
  mttsix: "\u{1D7FC}",
  mttthree: "\u{1D7F9}",
  mtttwo: "\u{1D7F8}",
  mttzero: "\u{1D7F6}",
  nHdownarrow: "\u{21DF}",
  nHuparrow: "\u{21DE}",
  natural: "\u{266E}",
  neg: "\u{00AC}",
  neovnwarrow: "\u{2931}",
  neovsearrow: "\u{292E}",
  neuter: "\u{26B2}",
  nexists: "\u{2204}",
  nvinfty: "\u{29DE}",
  nwovnearrow: "\u{2932}",
  obot: "\u{29BA}",
  obrbrak: "\u{23E0}",
  odotslashdot: "\u{29BC}",
  olcross: "\u{29BB}",
  parallelogram: "\u{25B1}",
  parallelogramblack: "\u{25B0}",
  pentagon: "\u{2B20}",
  pentagonblack: "\u{2B1F}",
  perps: "\u{2AE1}",
  postalmark: "\u{3012}",
  // NOTE \prime disabled to re-use MathJax's definition (['\u2032', {variantForm: true}])
  // TODO other primes (e.g., qprime) might need similar variantForm but xetex behavior is more complex
  // prime: '\u{2032}',
  profline: "\u{2312}",
  profsurf: "\u{2313}",
  qprime: "\u{2057}",
  quarternote: "\u{2669}",
  rangledownzigzagarrow: "\u{237C}",
  rbracelend: "\u{23AD}",
  rbracemid: "\u{23AC}",
  rbraceuend: "\u{23AB}",
  rbrackextender: "\u{23A5}",
  rbracklend: "\u{23A6}",
  rbrackuend: "\u{23A4}",
  rdiagovfdiag: "\u{292B}",
  rdiagovsearrow: "\u{2930}",
  revangle: "\u{29A3}",
  revangleubar: "\u{29A5}",
  revemptyset: "\u{29B0}",
  rightangle: "\u{221F}",
  rightanglemdot: "\u{299D}",
  rightanglesqr: "\u{299C}",
  rightdasharrow: "\u{21E2}",
  rightmoon: "\u{263D}",
  rightpentagon: "\u{2B54}",
  rightpentagonblack: "\u{2B53}",
  rightwhitearrow: "\u{21E8}",
  rparenextender: "\u{239F}",
  rparenlend: "\u{23A0}",
  rparenuend: "\u{239E}",
  rvboxline: "\u{23B9}",
  sansLmirrored: "\u{2143}",
  sansLturned: "\u{2142}",
  seovnearrow: "\u{292D}",
  sharp: "\u{266F}",
  sinewave: "\u{223F}",
  smallblacktriangleleft: "\u{25C2}",
  smallblacktriangleright: "\u{25B8}",
  smalltriangleleft: "\u{25C3}",
  smalltriangleright: "\u{25B9}",
  smblkdiamond: "\u{2B29}",
  smblklozenge: "\u{2B2A}",
  smblksquare: "\u{25AA}",
  smwhitestar: "\u{2B52}",
  smwhtcircle: "\u{25E6}",
  smwhtlozenge: "\u{2B2B}",
  smwhtsquare: "\u{25AB}",
  spadesuit: "\u{2660}",
  sphericalangle: "\u{2222}",
  sphericalangleup: "\u{29A1}",
  sqlozenge: "\u{2311}",
  sqrtbottom: "\u{23B7}",
  squarebotblack: "\u{2B13}",
  squarecrossfill: "\u{25A9}",
  squarehfill: "\u{25A4}",
  squarehvfill: "\u{25A6}",
  squareleftblack: "\u{25E7}",
  squarellblack: "\u{2B15}",
  squarellquad: "\u{25F1}",
  squarelrblack: "\u{25EA}",
  squarelrquad: "\u{25F2}",
  squareneswfill: "\u{25A8}",
  squarenwsefill: "\u{25A7}",
  squarerightblack: "\u{25E8}",
  squaretopblack: "\u{2B12}",
  squareulblack: "\u{25E9}",
  squareulquad: "\u{25F0}",
  squareurblack: "\u{2B14}",
  squareurquad: "\u{25F3}",
  squarevfill: "\u{25A5}",
  squoval: "\u{25A2}",
  strns: "\u{23E4}",
  subsetcirc: "\u{27C3}",
  sumbottom: "\u{23B3}",
  sumtop: "\u{23B2}",
  sun: "\u{263C}",
  supsetcirc: "\u{27C4}",
  surd: "\u{221A}",
  therefore: "\u{2234}",
  thermod: "\u{29E7}",
  threedangle: "\u{27C0}",
  tieinfty: "\u{29DD}",
  top: "\u{22A4}",
  topbot: "\u{2336}",
  topcir: "\u{2AF1}",
  topsemicircle: "\u{25E0}",
  trapezium: "\u{23E2}",
  trianglecdot: "\u{25EC}",
  triangledown: "\u{25BF}",
  triangleleftblack: "\u{25ED}",
  triangleodot: "\u{29CA}",
  trianglerightblack: "\u{25EE}",
  triangles: "\u{29CC}",
  triangleubar: "\u{29CB}",
  trprime: "\u{2034}",
  turnangle: "\u{29A2}",
  turnednot: "\u{2319}",
  twolowline: "\u{2017}",
  twonotes: "\u{266B}",
  ubrbrak: "\u{23E1}",
  ularc: "\u{25DC}",
  ulblacktriangle: "\u{25E4}",
  ultriangle: "\u{25F8}",
  unicodecdots: "\u{22EF}",
  unicodeellipsis: "\u{2026}",
  uparrowoncircle: "\u{29BD}",
  upbackepsilon: "\u{03F6}",
  updasharrow: "\u{21E1}",
  updownarrowbar: "\u{21A8}",
  uprightcurvearrow: "\u{2934}",
  upwhitearrow: "\u{21E7}",
  urarc: "\u{25DD}",
  urblacktriangle: "\u{25E5}",
  urtriangle: "\u{25F9}",
  varcarriagereturn: "\u{23CE}",
  varclubsuit: "\u{2667}",
  vardiamondsuit: "\u{2666}",
  varheartsuit: "\u{2665}",
  varhexagon: "\u{2B21}",
  varhexagonblack: "\u{2B22}",
  varhexagonlrbonds: "\u{232C}",
  varlrtriangle: "\u{22BF}",
  varnothing: "\u{2205}",
  varspadesuit: "\u{2664}",
  varstar: "\u{2736}",
  vbraceextender: "\u{23AA}",
  viewdata: "\u{2317}",
  vrectangle: "\u{25AF}",
  vrectangleblack: "\u{25AE}",
  vysmblksquare: "\u{2B1D}",
  vysmwhtsquare: "\u{2B1E}",
  vzigzag: "\u{299A}",
  whitearrowupfrombar: "\u{21EA}",
  whiteinwhitetriangle: "\u{27C1}",
  whitepointerleft: "\u{25C5}",
  whitepointerright: "\u{25BB}",
  whthorzoval: "\u{2B2D}",
  whtvertoval: "\u{2B2F}",
  wideangledown: "\u{29A6}",
  wideangleup: "\u{29A7}",
});

new CharacterMap("unicode-math-mathchar0mo", ParseMethods.mathchar0mo, {
  // \mathop
  Bbbsum: ["\u{2140}", { texClass: TEXCLASS.OP, movesupsub: true }],
  Join: ["\u{2A1D}", { texClass: TEXCLASS.OP, movesupsub: true }],
  arabichad: ["\u{1EEF1}", { texClass: TEXCLASS.OP, movesupsub: true }],
  arabicmaj: ["\u{1EEF0}", { texClass: TEXCLASS.OP, movesupsub: true }],
  awint: ["\u{2A11}", { texClass: TEXCLASS.OP }],
  bigbot: ["\u{27D8}", { texClass: TEXCLASS.OP, movesupsub: true }],
  bigcap: ["\u{22C2}", { texClass: TEXCLASS.OP, movesupsub: true }],
  bigcup: ["\u{22C3}", { texClass: TEXCLASS.OP, movesupsub: true }],
  bigcupdot: ["\u{2A03}", { texClass: TEXCLASS.OP, movesupsub: true }],
  biginterleave: ["\u{2AFC}", { texClass: TEXCLASS.OP, movesupsub: true }],
  bigodot: ["\u{2A00}", { texClass: TEXCLASS.OP, movesupsub: true }],
  bigoplus: ["\u{2A01}", { texClass: TEXCLASS.OP, movesupsub: true }],
  bigotimes: ["\u{2A02}", { texClass: TEXCLASS.OP, movesupsub: true }],
  bigsqcap: ["\u{2A05}", { texClass: TEXCLASS.OP, movesupsub: true }],
  bigsqcup: ["\u{2A06}", { texClass: TEXCLASS.OP, movesupsub: true }],
  bigtalloblong: ["\u{2AFF}", { texClass: TEXCLASS.OP, movesupsub: true }],
  bigtimes: ["\u{2A09}", { texClass: TEXCLASS.OP, movesupsub: true }],
  bigtop: ["\u{27D9}", { texClass: TEXCLASS.OP, movesupsub: true }],
  bigtriangleleft: ["\u{2A1E}", { texClass: TEXCLASS.OP, movesupsub: true }],
  biguplus: ["\u{2A04}", { texClass: TEXCLASS.OP, movesupsub: true }],
  bigvee: ["\u{22C1}", { texClass: TEXCLASS.OP, movesupsub: true }],
  bigwedge: ["\u{22C0}", { texClass: TEXCLASS.OP, movesupsub: true }],
  cirfnint: ["\u{2A10}", { texClass: TEXCLASS.OP }],
  conjquant: ["\u{2A07}", { texClass: TEXCLASS.OP, movesupsub: true }],
  coprod: ["\u{2210}", { texClass: TEXCLASS.OP, movesupsub: true }],
  disjquant: ["\u{2A08}", { texClass: TEXCLASS.OP, movesupsub: true }],
  fint: ["\u{2A0F}", { texClass: TEXCLASS.OP }],
  fullouterjoin: ["\u{27D7}", { texClass: TEXCLASS.OP, movesupsub: true }],
  iiiint: ["\u{2A0C}", { texClass: TEXCLASS.OP }],
  iiint: ["\u{222D}", { texClass: TEXCLASS.OP }],
  iint: ["\u{222C}", { texClass: TEXCLASS.OP }],
  int: ["\u{222B}", { texClass: TEXCLASS.OP }],
  intBar: ["\u{2A0E}", { texClass: TEXCLASS.OP }],
  intbar: ["\u{2A0D}", { texClass: TEXCLASS.OP }],
  intcap: ["\u{2A19}", { texClass: TEXCLASS.OP }],
  intclockwise: ["\u{2231}", { texClass: TEXCLASS.OP }],
  intcup: ["\u{2A1A}", { texClass: TEXCLASS.OP }],
  intlarhk: ["\u{2A17}", { texClass: TEXCLASS.OP }],
  intx: ["\u{2A18}", { texClass: TEXCLASS.OP }],
  leftouterjoin: ["\u{27D5}", { texClass: TEXCLASS.OP, movesupsub: true }],
  lowint: ["\u{2A1C}", { texClass: TEXCLASS.OP }],
  modtwosum: ["\u{2A0A}", { texClass: TEXCLASS.OP, movesupsub: true }],
  npolint: ["\u{2A14}", { texClass: TEXCLASS.OP }],
  oiiint: ["\u{2230}", { texClass: TEXCLASS.OP }],
  oiint: ["\u{222F}", { texClass: TEXCLASS.OP }],
  oint: ["\u{222E}", { texClass: TEXCLASS.OP }],
  ointctrclockwise: ["\u{2233}", { texClass: TEXCLASS.OP }],
  pointint: ["\u{2A15}", { texClass: TEXCLASS.OP }],
  prod: ["\u{220F}", { texClass: TEXCLASS.OP, movesupsub: true }],
  rightouterjoin: ["\u{27D6}", { texClass: TEXCLASS.OP, movesupsub: true }],
  rppolint: ["\u{2A12}", { texClass: TEXCLASS.OP }],
  scpolint: ["\u{2A13}", { texClass: TEXCLASS.OP }],
  sqint: ["\u{2A16}", { texClass: TEXCLASS.OP }],
  sum: ["\u{2211}", { texClass: TEXCLASS.OP, movesupsub: true }],
  sumint: ["\u{2A0B}", { texClass: TEXCLASS.OP }],
  upint: ["\u{2A1B}", { texClass: TEXCLASS.OP }],
  varointclockwise: ["\u{2232}", { texClass: TEXCLASS.OP }],
  xbsol: ["\u{29F9}", { texClass: TEXCLASS.OP, movesupsub: true }],
  xsol: ["\u{29F8}", { texClass: TEXCLASS.OP, movesupsub: true }],
  zcmp: ["\u{2A1F}", { texClass: TEXCLASS.OP, movesupsub: true }],
  zpipe: ["\u{2A20}", { texClass: TEXCLASS.OP, movesupsub: true }],
  zproject: ["\u{2A21}", { texClass: TEXCLASS.OP, movesupsub: true }],
  // \mathbin
  Cap: ["\u{22D2}", { texClass: TEXCLASS.BIN }],
  Cup: ["\u{22D3}", { texClass: TEXCLASS.BIN }],
  Otimes: ["\u{2A37}", { texClass: TEXCLASS.BIN }],
  Sqcap: ["\u{2A4E}", { texClass: TEXCLASS.BIN }],
  Sqcup: ["\u{2A4F}", { texClass: TEXCLASS.BIN }],
  Vee: ["\u{2A54}", { texClass: TEXCLASS.BIN }],
  Wedge: ["\u{2A53}", { texClass: TEXCLASS.BIN }],
  amalg: ["\u{2A3F}", { texClass: TEXCLASS.BIN }],
  ast: ["\u{2217}", { texClass: TEXCLASS.BIN }],
  barcap: ["\u{2A43}", { texClass: TEXCLASS.BIN }],
  barcup: ["\u{2A42}", { texClass: TEXCLASS.BIN }],
  barvee: ["\u{22BD}", { texClass: TEXCLASS.BIN }],
  barwedge: ["\u{22BC}", { texClass: TEXCLASS.BIN }],
  bigslopedvee: ["\u{2A57}", { texClass: TEXCLASS.BIN }],
  bigslopedwedge: ["\u{2A58}", { texClass: TEXCLASS.BIN }],
  bigtriangleup: ["\u{25B3}", { texClass: TEXCLASS.BIN }],
  blackhourglass: ["\u{29D7}", { texClass: TEXCLASS.BIN }],
  boxast: ["\u{29C6}", { texClass: TEXCLASS.BIN }],
  boxbar: ["\u{25EB}", { texClass: TEXCLASS.BIN }],
  boxbox: ["\u{29C8}", { texClass: TEXCLASS.BIN }],
  boxbslash: ["\u{29C5}", { texClass: TEXCLASS.BIN }],
  boxcircle: ["\u{29C7}", { texClass: TEXCLASS.BIN }],
  boxdiag: ["\u{29C4}", { texClass: TEXCLASS.BIN }],
  boxdot: ["\u{22A1}", { texClass: TEXCLASS.BIN }],
  boxminus: ["\u{229F}", { texClass: TEXCLASS.BIN }],
  boxplus: ["\u{229E}", { texClass: TEXCLASS.BIN }],
  boxtimes: ["\u{22A0}", { texClass: TEXCLASS.BIN }],
  btimes: ["\u{2A32}", { texClass: TEXCLASS.BIN }],
  cap: ["\u{2229}", { texClass: TEXCLASS.BIN }],
  capbarcup: ["\u{2A49}", { texClass: TEXCLASS.BIN }],
  capdot: ["\u{2A40}", { texClass: TEXCLASS.BIN }],
  capovercup: ["\u{2A47}", { texClass: TEXCLASS.BIN }],
  capwedge: ["\u{2A44}", { texClass: TEXCLASS.BIN }],
  cdot: ["\u{22C5}", { texClass: TEXCLASS.BIN }],
  cdotp: ["\u{00B7}", { texClass: TEXCLASS.BIN }],
  circledast: ["\u{229B}", { texClass: TEXCLASS.BIN }],
  circledcirc: ["\u{229A}", { texClass: TEXCLASS.BIN }],
  circleddash: ["\u{229D}", { texClass: TEXCLASS.BIN }],
  circledequal: ["\u{229C}", { texClass: TEXCLASS.BIN }],
  circledparallel: ["\u{29B7}", { texClass: TEXCLASS.BIN }],
  circledvert: ["\u{29B6}", { texClass: TEXCLASS.BIN }],
  circlehbar: ["\u{29B5}", { texClass: TEXCLASS.BIN }],
  closedvarcap: ["\u{2A4D}", { texClass: TEXCLASS.BIN }],
  closedvarcup: ["\u{2A4C}", { texClass: TEXCLASS.BIN }],
  closedvarcupsmashprod: ["\u{2A50}", { texClass: TEXCLASS.BIN }],
  commaminus: ["\u{2A29}", { texClass: TEXCLASS.BIN }],
  concavediamond: ["\u{27E1}", { texClass: TEXCLASS.BIN }],
  concavediamondtickleft: ["\u{27E2}", { texClass: TEXCLASS.BIN }],
  concavediamondtickright: ["\u{27E3}", { texClass: TEXCLASS.BIN }],
  cup: ["\u{222A}", { texClass: TEXCLASS.BIN }],
  cupbarcap: ["\u{2A48}", { texClass: TEXCLASS.BIN }],
  cupdot: ["\u{228D}", { texClass: TEXCLASS.BIN }],
  cupleftarrow: ["\u{228C}", { texClass: TEXCLASS.BIN }],
  cupovercap: ["\u{2A46}", { texClass: TEXCLASS.BIN }],
  cupvee: ["\u{2A45}", { texClass: TEXCLASS.BIN }],
  curlyvee: ["\u{22CE}", { texClass: TEXCLASS.BIN }],
  curlywedge: ["\u{22CF}", { texClass: TEXCLASS.BIN }],
  dagger: ["\u{2020}", { texClass: TEXCLASS.BIN }],
  ddagger: ["\u{2021}", { texClass: TEXCLASS.BIN }],
  div: ["\u{00F7}", { texClass: TEXCLASS.BIN }],
  divideontimes: ["\u{22C7}", { texClass: TEXCLASS.BIN }],
  divslash: ["\u{2215}", { texClass: TEXCLASS.BIN }],
  dotminus: ["\u{2238}", { texClass: TEXCLASS.BIN }],
  dotplus: ["\u{2214}", { texClass: TEXCLASS.BIN }],
  dottimes: ["\u{2A30}", { texClass: TEXCLASS.BIN }],
  doublebarvee: ["\u{2A62}", { texClass: TEXCLASS.BIN }],
  doublebarwedge: ["\u{2A5E}", { texClass: TEXCLASS.BIN }],
  doubleplus: ["\u{29FA}", { texClass: TEXCLASS.BIN }],
  dsol: ["\u{29F6}", { texClass: TEXCLASS.BIN }],
  dsub: ["\u{2A64}", { texClass: TEXCLASS.BIN }],
  eqqplus: ["\u{2A71}", { texClass: TEXCLASS.BIN }],
  fcmp: ["\u{2A3E}", { texClass: TEXCLASS.BIN }],
  fracslash: ["\u{2044}", { texClass: TEXCLASS.BIN }],
  hourglass: ["\u{29D6}", { texClass: TEXCLASS.BIN }],
  intercal: ["\u{22BA}", { texClass: TEXCLASS.BIN }],
  interleave: ["\u{2AF4}", { texClass: TEXCLASS.BIN }],
  intprod: ["\u{2A3C}", { texClass: TEXCLASS.BIN }],
  intprodr: ["\u{2A3D}", { texClass: TEXCLASS.BIN }],
  invlazys: ["\u{223E}", { texClass: TEXCLASS.BIN }],
  leftthreetimes: ["\u{22CB}", { texClass: TEXCLASS.BIN }],
  lozengeminus: ["\u{27E0}", { texClass: TEXCLASS.BIN }],
  ltimes: ["\u{22C9}", { texClass: TEXCLASS.BIN }],
  mathplus: ["\u{002B}", { texClass: TEXCLASS.BIN }],
  mdlgblklozenge: ["\u{29EB}", { texClass: TEXCLASS.BIN }],
  mdlgwhtcircle: ["\u{25CB}", { texClass: TEXCLASS.BIN }],
  midbarvee: ["\u{2A5D}", { texClass: TEXCLASS.BIN }],
  midbarwedge: ["\u{2A5C}", { texClass: TEXCLASS.BIN }],
  minus: ["\u{2212}", { texClass: TEXCLASS.BIN }],
  minusdot: ["\u{2A2A}", { texClass: TEXCLASS.BIN }],
  minusfdots: ["\u{2A2B}", { texClass: TEXCLASS.BIN }],
  minusrdots: ["\u{2A2C}", { texClass: TEXCLASS.BIN }],
  mp: ["\u{2213}", { texClass: TEXCLASS.BIN }],
  nhVvert: ["\u{2AF5}", { texClass: TEXCLASS.BIN }],
  obar: ["\u{233D}", { texClass: TEXCLASS.BIN }],
  obslash: ["\u{29B8}", { texClass: TEXCLASS.BIN }],
  odiv: ["\u{2A38}", { texClass: TEXCLASS.BIN }],
  odot: ["\u{2299}", { texClass: TEXCLASS.BIN }],
  ogreaterthan: ["\u{29C1}", { texClass: TEXCLASS.BIN }],
  olessthan: ["\u{29C0}", { texClass: TEXCLASS.BIN }],
  ominus: ["\u{2296}", { texClass: TEXCLASS.BIN }],
  operp: ["\u{29B9}", { texClass: TEXCLASS.BIN }],
  oplus: ["\u{2295}", { texClass: TEXCLASS.BIN }],
  opluslhrim: ["\u{2A2D}", { texClass: TEXCLASS.BIN }],
  oplusrhrim: ["\u{2A2E}", { texClass: TEXCLASS.BIN }],
  oslash: ["\u{2298}", { texClass: TEXCLASS.BIN }],
  otimes: ["\u{2297}", { texClass: TEXCLASS.BIN }],
  otimeshat: ["\u{2A36}", { texClass: TEXCLASS.BIN }],
  otimeslhrim: ["\u{2A34}", { texClass: TEXCLASS.BIN }],
  otimesrhrim: ["\u{2A35}", { texClass: TEXCLASS.BIN }],
  plusdot: ["\u{2A25}", { texClass: TEXCLASS.BIN }],
  pluseqq: ["\u{2A72}", { texClass: TEXCLASS.BIN }],
  plushat: ["\u{2A23}", { texClass: TEXCLASS.BIN }],
  plussim: ["\u{2A26}", { texClass: TEXCLASS.BIN }],
  plussubtwo: ["\u{2A27}", { texClass: TEXCLASS.BIN }],
  plustrif: ["\u{2A28}", { texClass: TEXCLASS.BIN }],
  pm: ["\u{00B1}", { texClass: TEXCLASS.BIN }],
  rightthreetimes: ["\u{22CC}", { texClass: TEXCLASS.BIN }],
  ringplus: ["\u{2A22}", { texClass: TEXCLASS.BIN }],
  rsolbar: ["\u{29F7}", { texClass: TEXCLASS.BIN }],
  rsub: ["\u{2A65}", { texClass: TEXCLASS.BIN }],
  rtimes: ["\u{22CA}", { texClass: TEXCLASS.BIN }],
  setminus: ["\u{29F5}", { texClass: TEXCLASS.BIN }],
  shuffle: ["\u{29E2}", { texClass: TEXCLASS.BIN }],
  simplus: ["\u{2A24}", { texClass: TEXCLASS.BIN }],
  smallsetminus: ["\u{2216}", { texClass: TEXCLASS.BIN }],
  smashtimes: ["\u{2A33}", { texClass: TEXCLASS.BIN }],
  smblkcircle: ["\u{2022}", { texClass: TEXCLASS.BIN }],
  smwhtdiamond: ["\u{22C4}", { texClass: TEXCLASS.BIN }],
  sqcap: ["\u{2293}", { texClass: TEXCLASS.BIN }],
  sqcup: ["\u{2294}", { texClass: TEXCLASS.BIN }],
  sslash: ["\u{2AFD}", { texClass: TEXCLASS.BIN }],
  star: ["\u{22C6}", { texClass: TEXCLASS.BIN }],
  talloblong: ["\u{2AFE}", { texClass: TEXCLASS.BIN }],
  threedotcolon: ["\u{2AF6}", { texClass: TEXCLASS.BIN }],
  tieconcat: ["\u{2040}", { texClass: TEXCLASS.BIN }],
  times: ["\u{00D7}", { texClass: TEXCLASS.BIN }],
  timesbar: ["\u{2A31}", { texClass: TEXCLASS.BIN }],
  tminus: ["\u{29FF}", { texClass: TEXCLASS.BIN }],
  tplus: ["\u{29FE}", { texClass: TEXCLASS.BIN }],
  triangleleft: ["\u{25C1}", { texClass: TEXCLASS.BIN }],
  triangleminus: ["\u{2A3A}", { texClass: TEXCLASS.BIN }],
  triangleplus: ["\u{2A39}", { texClass: TEXCLASS.BIN }],
  triangleright: ["\u{25B7}", { texClass: TEXCLASS.BIN }],
  triangleserifs: ["\u{29CD}", { texClass: TEXCLASS.BIN }],
  triangletimes: ["\u{2A3B}", { texClass: TEXCLASS.BIN }],
  tripleplus: ["\u{29FB}", { texClass: TEXCLASS.BIN }],
  trslash: ["\u{2AFB}", { texClass: TEXCLASS.BIN }],
  twocaps: ["\u{2A4B}", { texClass: TEXCLASS.BIN }],
  twocups: ["\u{2A4A}", { texClass: TEXCLASS.BIN }],
  uminus: ["\u{2A41}", { texClass: TEXCLASS.BIN }],
  upand: ["\u{214B}", { texClass: TEXCLASS.BIN }],
  uplus: ["\u{228E}", { texClass: TEXCLASS.BIN }],
  varbarwedge: ["\u{2305}", { texClass: TEXCLASS.BIN }],
  vardoublebarwedge: ["\u{2306}", { texClass: TEXCLASS.BIN }],
  varveebar: ["\u{2A61}", { texClass: TEXCLASS.BIN }],
  vectimes: ["\u{2A2F}", { texClass: TEXCLASS.BIN }],
  vee: ["\u{2228}", { texClass: TEXCLASS.BIN }],
  veebar: ["\u{22BB}", { texClass: TEXCLASS.BIN }],
  veedot: ["\u{27C7}", { texClass: TEXCLASS.BIN }],
  veedoublebar: ["\u{2A63}", { texClass: TEXCLASS.BIN }],
  veemidvert: ["\u{2A5B}", { texClass: TEXCLASS.BIN }],
  veeodot: ["\u{2A52}", { texClass: TEXCLASS.BIN }],
  veeonvee: ["\u{2A56}", { texClass: TEXCLASS.BIN }],
  vysmblkcircle: ["\u{2219}", { texClass: TEXCLASS.BIN }],
  vysmwhtcircle: ["\u{2218}", { texClass: TEXCLASS.BIN }],
  wedge: ["\u{2227}", { texClass: TEXCLASS.BIN }],
  wedgebar: ["\u{2A5F}", { texClass: TEXCLASS.BIN }],
  wedgedot: ["\u{27D1}", { texClass: TEXCLASS.BIN }],
  wedgedoublebar: ["\u{2A60}", { texClass: TEXCLASS.BIN }],
  wedgemidvert: ["\u{2A5A}", { texClass: TEXCLASS.BIN }],
  wedgeodot: ["\u{2A51}", { texClass: TEXCLASS.BIN }],
  wedgeonwedge: ["\u{2A55}", { texClass: TEXCLASS.BIN }],
  whitesquaretickleft: ["\u{27E4}", { texClass: TEXCLASS.BIN }],
  whitesquaretickright: ["\u{27E5}", { texClass: TEXCLASS.BIN }],
  wr: ["\u{2240}", { texClass: TEXCLASS.BIN }],
  // \mathpunct
  mathcolon: ["\u{003A}", { texClass: TEXCLASS.PUNCT }],
  mathcomma: ["\u{002C}", { texClass: TEXCLASS.PUNCT }],
  mathsemicolon: ["\u{003B}", { texClass: TEXCLASS.PUNCT }],
  // \mathrel
  APLnotslash: ["\u{233F}", { texClass: TEXCLASS.REL }],
  Barv: ["\u{2AE7}", { texClass: TEXCLASS.REL }],
  Bumpeq: ["\u{224E}", { texClass: TEXCLASS.REL }],
  Colon: ["\u{2237}", { texClass: TEXCLASS.REL }],
  Coloneq: ["\u{2A74}", { texClass: TEXCLASS.REL }],
  DDownarrow: ["\u{27F1}", { texClass: TEXCLASS.REL }],
  DashV: ["\u{2AE5}", { texClass: TEXCLASS.REL }],
  DashVDash: ["\u{27DA}", { texClass: TEXCLASS.REL }],
  Dashv: ["\u{2AE4}", { texClass: TEXCLASS.REL }],
  Ddownarrow: ["\u{290B}", { texClass: TEXCLASS.REL }],
  Doteq: ["\u{2251}", { texClass: TEXCLASS.REL }],
  Downarrow: ["\u{21D3}", { texClass: TEXCLASS.REL }],
  Equiv: ["\u{2263}", { texClass: TEXCLASS.REL }],
  Gt: ["\u{2AA2}", { texClass: TEXCLASS.REL }],
  LLeftarrow: ["\u{2B45}", { texClass: TEXCLASS.REL }],
  Ldsh: ["\u{21B2}", { texClass: TEXCLASS.REL }],
  Leftarrow: ["\u{21D0}", { texClass: TEXCLASS.REL }],
  Leftrightarrow: ["\u{21D4}", { texClass: TEXCLASS.REL }],
  Lleftarrow: ["\u{21DA}", { texClass: TEXCLASS.REL }],
  Longleftarrow: ["\u{27F8}", { texClass: TEXCLASS.REL }],
  Longleftrightarrow: ["\u{27FA}", { texClass: TEXCLASS.REL }],
  Longmapsfrom: ["\u{27FD}", { texClass: TEXCLASS.REL }],
  Longmapsto: ["\u{27FE}", { texClass: TEXCLASS.REL }],
  Longrightarrow: ["\u{27F9}", { texClass: TEXCLASS.REL }],
  Lsh: ["\u{21B0}", { texClass: TEXCLASS.REL }],
  Lt: ["\u{2AA1}", { texClass: TEXCLASS.REL }],
  Mapsfrom: ["\u{2906}", { texClass: TEXCLASS.REL }],
  Mapsto: ["\u{2907}", { texClass: TEXCLASS.REL }],
  Nearrow: ["\u{21D7}", { texClass: TEXCLASS.REL }],
  Not: ["\u{2AEC}", { texClass: TEXCLASS.REL }],
  Nwarrow: ["\u{21D6}", { texClass: TEXCLASS.REL }],
  Prec: ["\u{2ABB}", { texClass: TEXCLASS.REL }],
  RRightarrow: ["\u{2B46}", { texClass: TEXCLASS.REL }],
  Rdsh: ["\u{21B3}", { texClass: TEXCLASS.REL }],
  Rightarrow: ["\u{21D2}", { texClass: TEXCLASS.REL }],
  Rrightarrow: ["\u{21DB}", { texClass: TEXCLASS.REL }],
  Rsh: ["\u{21B1}", { texClass: TEXCLASS.REL }],
  Searrow: ["\u{21D8}", { texClass: TEXCLASS.REL }],
  Subset: ["\u{22D0}", { texClass: TEXCLASS.REL }],
  Succ: ["\u{2ABC}", { texClass: TEXCLASS.REL }],
  Supset: ["\u{22D1}", { texClass: TEXCLASS.REL }],
  Swarrow: ["\u{21D9}", { texClass: TEXCLASS.REL }],
  UUparrow: ["\u{27F0}", { texClass: TEXCLASS.REL }],
  Uparrow: ["\u{21D1}", { texClass: TEXCLASS.REL }],
  Updownarrow: ["\u{21D5}", { texClass: TEXCLASS.REL }],
  Uuparrow: ["\u{290A}", { texClass: TEXCLASS.REL }],
  VDash: ["\u{22AB}", { texClass: TEXCLASS.REL }],
  Vbar: ["\u{2AEB}", { texClass: TEXCLASS.REL }],
  Vdash: ["\u{22A9}", { texClass: TEXCLASS.REL }],
  Vvdash: ["\u{22AA}", { texClass: TEXCLASS.REL }],
  acwcirclearrow: ["\u{2940}", { texClass: TEXCLASS.REL }],
  acwgapcirclearrow: ["\u{27F2}", { texClass: TEXCLASS.REL }],
  acwleftarcarrow: ["\u{2939}", { texClass: TEXCLASS.REL }],
  acwoverarcarrow: ["\u{293A}", { texClass: TEXCLASS.REL }],
  acwunderarcarrow: ["\u{293B}", { texClass: TEXCLASS.REL }],
  adots: ["\u{22F0}", { texClass: TEXCLASS.REL }],
  approx: ["\u{2248}", { texClass: TEXCLASS.REL }],
  approxeq: ["\u{224A}", { texClass: TEXCLASS.REL }],
  approxeqq: ["\u{2A70}", { texClass: TEXCLASS.REL }],
  approxident: ["\u{224B}", { texClass: TEXCLASS.REL }],
  arceq: ["\u{2258}", { texClass: TEXCLASS.REL }],
  assert: ["\u{22A6}", { texClass: TEXCLASS.REL }],
  asteq: ["\u{2A6E}", { texClass: TEXCLASS.REL }],
  asymp: ["\u{224D}", { texClass: TEXCLASS.REL }],
  bNot: ["\u{2AED}", { texClass: TEXCLASS.REL }],
  backcong: ["\u{224C}", { texClass: TEXCLASS.REL }],
  backsim: ["\u{223D}", { texClass: TEXCLASS.REL }],
  backsimeq: ["\u{22CD}", { texClass: TEXCLASS.REL }],
  bagmember: ["\u{22FF}", { texClass: TEXCLASS.REL }],
  barV: ["\u{2AEA}", { texClass: TEXCLASS.REL }],
  bardownharpoonleft: ["\u{2961}", { texClass: TEXCLASS.REL }],
  bardownharpoonright: ["\u{295D}", { texClass: TEXCLASS.REL }],
  barleftarrow: ["\u{21E4}", { texClass: TEXCLASS.REL }],
  barleftharpoondown: ["\u{2956}", { texClass: TEXCLASS.REL }],
  barleftharpoonup: ["\u{2952}", { texClass: TEXCLASS.REL }],
  barrightarrowdiamond: ["\u{2920}", { texClass: TEXCLASS.REL }],
  barrightharpoondown: ["\u{295F}", { texClass: TEXCLASS.REL }],
  barrightharpoonup: ["\u{295B}", { texClass: TEXCLASS.REL }],
  baruparrow: ["\u{2912}", { texClass: TEXCLASS.REL }],
  barupharpoonleft: ["\u{2958}", { texClass: TEXCLASS.REL }],
  barupharpoonright: ["\u{2954}", { texClass: TEXCLASS.REL }],
  between: ["\u{226C}", { texClass: TEXCLASS.REL }],
  bowtie: ["\u{22C8}", { texClass: TEXCLASS.REL }],
  bsimilarleftarrow: ["\u{2B41}", { texClass: TEXCLASS.REL }],
  bsimilarrightarrow: ["\u{2B47}", { texClass: TEXCLASS.REL }],
  bsolhsub: ["\u{27C8}", { texClass: TEXCLASS.REL }],
  bumpeq: ["\u{224F}", { texClass: TEXCLASS.REL }],
  bumpeqq: ["\u{2AAE}", { texClass: TEXCLASS.REL }],
  ccwundercurvearrow: ["\u{293F}", { texClass: TEXCLASS.REL }],
  cirbot: ["\u{27DF}", { texClass: TEXCLASS.REL }],
  circeq: ["\u{2257}", { texClass: TEXCLASS.REL }],
  circleonleftarrow: ["\u{2B30}", { texClass: TEXCLASS.REL }],
  circleonrightarrow: ["\u{21F4}", { texClass: TEXCLASS.REL }],
  cirmid: ["\u{2AEF}", { texClass: TEXCLASS.REL }],
  closure: ["\u{2050}", { texClass: TEXCLASS.REL }],
  coloneq: ["\u{2254}", { texClass: TEXCLASS.REL }],
  cong: ["\u{2245}", { texClass: TEXCLASS.REL }],
  congdot: ["\u{2A6D}", { texClass: TEXCLASS.REL }],
  csub: ["\u{2ACF}", { texClass: TEXCLASS.REL }],
  csube: ["\u{2AD1}", { texClass: TEXCLASS.REL }],
  csup: ["\u{2AD0}", { texClass: TEXCLASS.REL }],
  csupe: ["\u{2AD2}", { texClass: TEXCLASS.REL }],
  curlyeqprec: ["\u{22DE}", { texClass: TEXCLASS.REL }],
  curlyeqsucc: ["\u{22DF}", { texClass: TEXCLASS.REL }],
  curvearrowleft: ["\u{21B6}", { texClass: TEXCLASS.REL }],
  curvearrowleftplus: ["\u{293D}", { texClass: TEXCLASS.REL }],
  curvearrowright: ["\u{21B7}", { texClass: TEXCLASS.REL }],
  curvearrowrightminus: ["\u{293C}", { texClass: TEXCLASS.REL }],
  cwcirclearrow: ["\u{2941}", { texClass: TEXCLASS.REL }],
  cwgapcirclearrow: ["\u{27F3}", { texClass: TEXCLASS.REL }],
  cwrightarcarrow: ["\u{2938}", { texClass: TEXCLASS.REL }],
  cwundercurvearrow: ["\u{293E}", { texClass: TEXCLASS.REL }],
  dashV: ["\u{2AE3}", { texClass: TEXCLASS.REL }],
  dashVdash: ["\u{27DB}", { texClass: TEXCLASS.REL }],
  dashcolon: ["\u{2239}", { texClass: TEXCLASS.REL }],
  dashleftharpoondown: ["\u{296B}", { texClass: TEXCLASS.REL }],
  dashrightharpoondown: ["\u{296D}", { texClass: TEXCLASS.REL }],
  dashv: ["\u{22A3}", { texClass: TEXCLASS.REL }],
  dbkarrow: ["\u{290F}", { texClass: TEXCLASS.REL }],
  ddots: ["\u{22F1}", { texClass: TEXCLASS.REL }],
  ddotseq: ["\u{2A77}", { texClass: TEXCLASS.REL }],
  diamondleftarrow: ["\u{291D}", { texClass: TEXCLASS.REL }],
  diamondleftarrowbar: ["\u{291F}", { texClass: TEXCLASS.REL }],
  disin: ["\u{22F2}", { texClass: TEXCLASS.REL }],
  doteq: ["\u{2250}", { texClass: TEXCLASS.REL }],
  dotequiv: ["\u{2A67}", { texClass: TEXCLASS.REL }],
  dotsim: ["\u{2A6A}", { texClass: TEXCLASS.REL }],
  dotsminusdots: ["\u{223A}", { texClass: TEXCLASS.REL }],
  downarrow: ["\u{2193}", { texClass: TEXCLASS.REL }],
  downarrowbar: ["\u{2913}", { texClass: TEXCLASS.REL }],
  downarrowbarred: ["\u{2908}", { texClass: TEXCLASS.REL }],
  downdownarrows: ["\u{21CA}", { texClass: TEXCLASS.REL }],
  downfishtail: ["\u{297F}", { texClass: TEXCLASS.REL }],
  downharpoonleft: ["\u{21C3}", { texClass: TEXCLASS.REL }],
  downharpoonleftbar: ["\u{2959}", { texClass: TEXCLASS.REL }],
  downharpoonright: ["\u{21C2}", { texClass: TEXCLASS.REL }],
  downharpoonrightbar: ["\u{2955}", { texClass: TEXCLASS.REL }],
  downharpoonsleftright: ["\u{2965}", { texClass: TEXCLASS.REL }],
  downuparrows: ["\u{21F5}", { texClass: TEXCLASS.REL }],
  downupharpoonsleftright: ["\u{296F}", { texClass: TEXCLASS.REL }],
  downzigzagarrow: ["\u{21AF}", { texClass: TEXCLASS.REL }],
  drbkarrow: ["\u{2910}", { texClass: TEXCLASS.REL }],
  dualmap: ["\u{29DF}", { texClass: TEXCLASS.REL }],
  egsdot: ["\u{2A98}", { texClass: TEXCLASS.REL }],
  elsdot: ["\u{2A97}", { texClass: TEXCLASS.REL }],
  eparsl: ["\u{29E3}", { texClass: TEXCLASS.REL }],
  eqcirc: ["\u{2256}", { texClass: TEXCLASS.REL }],
  eqcolon: ["\u{2255}", { texClass: TEXCLASS.REL }],
  eqdef: ["\u{225D}", { texClass: TEXCLASS.REL }],
  eqdot: ["\u{2A66}", { texClass: TEXCLASS.REL }],
  eqeq: ["\u{2A75}", { texClass: TEXCLASS.REL }],
  eqeqeq: ["\u{2A76}", { texClass: TEXCLASS.REL }],
  eqgtr: ["\u{22DD}", { texClass: TEXCLASS.REL }],
  eqless: ["\u{22DC}", { texClass: TEXCLASS.REL }],
  eqqgtr: ["\u{2A9A}", { texClass: TEXCLASS.REL }],
  eqqless: ["\u{2A99}", { texClass: TEXCLASS.REL }],
  eqqsim: ["\u{2A73}", { texClass: TEXCLASS.REL }],
  eqqslantgtr: ["\u{2A9C}", { texClass: TEXCLASS.REL }],
  eqqslantless: ["\u{2A9B}", { texClass: TEXCLASS.REL }],
  eqsim: ["\u{2242}", { texClass: TEXCLASS.REL }],
  eqslantgtr: ["\u{2A96}", { texClass: TEXCLASS.REL }],
  eqslantless: ["\u{2A95}", { texClass: TEXCLASS.REL }],
  equal: ["\u{003D}", { texClass: TEXCLASS.REL }],
  equalleftarrow: ["\u{2B40}", { texClass: TEXCLASS.REL }],
  equalparallel: ["\u{22D5}", { texClass: TEXCLASS.REL }],
  equalrightarrow: ["\u{2971}", { texClass: TEXCLASS.REL }],
  equiv: ["\u{2261}", { texClass: TEXCLASS.REL }],
  equivDD: ["\u{2A78}", { texClass: TEXCLASS.REL }],
  equivVert: ["\u{2A68}", { texClass: TEXCLASS.REL }],
  equivVvert: ["\u{2A69}", { texClass: TEXCLASS.REL }],
  eqvparsl: ["\u{29E5}", { texClass: TEXCLASS.REL }],
  fallingdotseq: ["\u{2252}", { texClass: TEXCLASS.REL }],
  fbowtie: ["\u{29D3}", { texClass: TEXCLASS.REL }],
  forks: ["\u{2ADC}", { texClass: TEXCLASS.REL }],
  forksnot: ["\u{2ADD}", { texClass: TEXCLASS.REL }],
  forkv: ["\u{2AD9}", { texClass: TEXCLASS.REL }],
  frown: ["\u{2322}", { texClass: TEXCLASS.REL }],
  geq: ["\u{2265}", { texClass: TEXCLASS.REL }],
  geqq: ["\u{2267}", { texClass: TEXCLASS.REL }],
  geqqslant: ["\u{2AFA}", { texClass: TEXCLASS.REL }],
  geqslant: ["\u{2A7E}", { texClass: TEXCLASS.REL }],
  gescc: ["\u{2AA9}", { texClass: TEXCLASS.REL }],
  gesdot: ["\u{2A80}", { texClass: TEXCLASS.REL }],
  gesdoto: ["\u{2A82}", { texClass: TEXCLASS.REL }],
  gesdotol: ["\u{2A84}", { texClass: TEXCLASS.REL }],
  gesles: ["\u{2A94}", { texClass: TEXCLASS.REL }],
  gg: ["\u{226B}", { texClass: TEXCLASS.REL }],
  ggg: ["\u{22D9}", { texClass: TEXCLASS.REL }],
  gggnest: ["\u{2AF8}", { texClass: TEXCLASS.REL }],
  glE: ["\u{2A92}", { texClass: TEXCLASS.REL }],
  gla: ["\u{2AA5}", { texClass: TEXCLASS.REL }],
  gleichstark: ["\u{29E6}", { texClass: TEXCLASS.REL }],
  glj: ["\u{2AA4}", { texClass: TEXCLASS.REL }],
  gnapprox: ["\u{2A8A}", { texClass: TEXCLASS.REL }],
  gneq: ["\u{2A88}", { texClass: TEXCLASS.REL }],
  gneqq: ["\u{2269}", { texClass: TEXCLASS.REL }],
  gnsim: ["\u{22E7}", { texClass: TEXCLASS.REL }],
  greater: ["\u{003E}", { texClass: TEXCLASS.REL }],
  gsime: ["\u{2A8E}", { texClass: TEXCLASS.REL }],
  gsiml: ["\u{2A90}", { texClass: TEXCLASS.REL }],
  gtcc: ["\u{2AA7}", { texClass: TEXCLASS.REL }],
  gtcir: ["\u{2A7A}", { texClass: TEXCLASS.REL }],
  gtquest: ["\u{2A7C}", { texClass: TEXCLASS.REL }],
  gtrapprox: ["\u{2A86}", { texClass: TEXCLASS.REL }],
  gtrarr: ["\u{2978}", { texClass: TEXCLASS.REL }],
  gtrdot: ["\u{22D7}", { texClass: TEXCLASS.REL }],
  gtreqless: ["\u{22DB}", { texClass: TEXCLASS.REL }],
  gtreqqless: ["\u{2A8C}", { texClass: TEXCLASS.REL }],
  gtrless: ["\u{2277}", { texClass: TEXCLASS.REL }],
  gtrsim: ["\u{2273}", { texClass: TEXCLASS.REL }],
  hatapprox: ["\u{2A6F}", { texClass: TEXCLASS.REL }],
  hknearrow: ["\u{2924}", { texClass: TEXCLASS.REL }],
  hknwarrow: ["\u{2923}", { texClass: TEXCLASS.REL }],
  hksearrow: ["\u{2925}", { texClass: TEXCLASS.REL }],
  hkswarrow: ["\u{2926}", { texClass: TEXCLASS.REL }],
  hookleftarrow: ["\u{21A9}", { texClass: TEXCLASS.REL }],
  hookrightarrow: ["\u{21AA}", { texClass: TEXCLASS.REL }],
  imageof: ["\u{22B7}", { texClass: TEXCLASS.REL }],
  in: ["\u{2208}", { texClass: TEXCLASS.REL }],
  isinE: ["\u{22F9}", { texClass: TEXCLASS.REL }],
  isindot: ["\u{22F5}", { texClass: TEXCLASS.REL }],
  isinobar: ["\u{22F7}", { texClass: TEXCLASS.REL }],
  isins: ["\u{22F4}", { texClass: TEXCLASS.REL }],
  isinvb: ["\u{22F8}", { texClass: TEXCLASS.REL }],
  kernelcontraction: ["\u{223B}", { texClass: TEXCLASS.REL }],
  lat: ["\u{2AAB}", { texClass: TEXCLASS.REL }],
  late: ["\u{2AAD}", { texClass: TEXCLASS.REL }],
  leftarrow: ["\u{2190}", { texClass: TEXCLASS.REL }],
  leftarrowapprox: ["\u{2B4A}", { texClass: TEXCLASS.REL }],
  leftarrowbackapprox: ["\u{2B42}", { texClass: TEXCLASS.REL }],
  leftarrowbsimilar: ["\u{2B4B}", { texClass: TEXCLASS.REL }],
  leftarrowless: ["\u{2977}", { texClass: TEXCLASS.REL }],
  leftarrowonoplus: ["\u{2B32}", { texClass: TEXCLASS.REL }],
  leftarrowplus: ["\u{2946}", { texClass: TEXCLASS.REL }],
  leftarrowshortrightarrow: ["\u{2943}", { texClass: TEXCLASS.REL }],
  leftarrowsimilar: ["\u{2973}", { texClass: TEXCLASS.REL }],
  leftarrowsubset: ["\u{297A}", { texClass: TEXCLASS.REL }],
  leftarrowtail: ["\u{21A2}", { texClass: TEXCLASS.REL }],
  leftarrowtriangle: ["\u{21FD}", { texClass: TEXCLASS.REL }],
  leftarrowx: ["\u{2B3E}", { texClass: TEXCLASS.REL }],
  leftbkarrow: ["\u{290C}", { texClass: TEXCLASS.REL }],
  leftcurvedarrow: ["\u{2B3F}", { texClass: TEXCLASS.REL }],
  leftdbkarrow: ["\u{290E}", { texClass: TEXCLASS.REL }],
  leftdbltail: ["\u{291B}", { texClass: TEXCLASS.REL }],
  leftdotarrow: ["\u{2B38}", { texClass: TEXCLASS.REL }],
  leftdowncurvedarrow: ["\u{2936}", { texClass: TEXCLASS.REL }],
  leftfishtail: ["\u{297C}", { texClass: TEXCLASS.REL }],
  leftharpoondown: ["\u{21BD}", { texClass: TEXCLASS.REL }],
  leftharpoondownbar: ["\u{295E}", { texClass: TEXCLASS.REL }],
  leftharpoonsupdown: ["\u{2962}", { texClass: TEXCLASS.REL }],
  leftharpoonup: ["\u{21BC}", { texClass: TEXCLASS.REL }],
  leftharpoonupbar: ["\u{295A}", { texClass: TEXCLASS.REL }],
  leftharpoonupdash: ["\u{296A}", { texClass: TEXCLASS.REL }],
  leftleftarrows: ["\u{21C7}", { texClass: TEXCLASS.REL }],
  leftrightarrow: ["\u{2194}", { texClass: TEXCLASS.REL }],
  leftrightarrowcircle: ["\u{2948}", { texClass: TEXCLASS.REL }],
  leftrightarrows: ["\u{21C6}", { texClass: TEXCLASS.REL }],
  leftrightarrowtriangle: ["\u{21FF}", { texClass: TEXCLASS.REL }],
  leftrightharpoondowndown: ["\u{2950}", { texClass: TEXCLASS.REL }],
  leftrightharpoondownup: ["\u{294B}", { texClass: TEXCLASS.REL }],
  leftrightharpoons: ["\u{21CB}", { texClass: TEXCLASS.REL }],
  leftrightharpoonsdown: ["\u{2967}", { texClass: TEXCLASS.REL }],
  leftrightharpoonsup: ["\u{2966}", { texClass: TEXCLASS.REL }],
  leftrightharpoonupdown: ["\u{294A}", { texClass: TEXCLASS.REL }],
  leftrightharpoonupup: ["\u{294E}", { texClass: TEXCLASS.REL }],
  leftrightsquigarrow: ["\u{21AD}", { texClass: TEXCLASS.REL }],
  leftsquigarrow: ["\u{21DC}", { texClass: TEXCLASS.REL }],
  lefttail: ["\u{2919}", { texClass: TEXCLASS.REL }],
  leftthreearrows: ["\u{2B31}", { texClass: TEXCLASS.REL }],
  leftwavearrow: ["\u{219C}", { texClass: TEXCLASS.REL }],
  leq: ["\u{2264}", { texClass: TEXCLASS.REL }],
  leqq: ["\u{2266}", { texClass: TEXCLASS.REL }],
  leqqslant: ["\u{2AF9}", { texClass: TEXCLASS.REL }],
  leqslant: ["\u{2A7D}", { texClass: TEXCLASS.REL }],
  lescc: ["\u{2AA8}", { texClass: TEXCLASS.REL }],
  lesdot: ["\u{2A7F}", { texClass: TEXCLASS.REL }],
  lesdoto: ["\u{2A81}", { texClass: TEXCLASS.REL }],
  lesdotor: ["\u{2A83}", { texClass: TEXCLASS.REL }],
  lesges: ["\u{2A93}", { texClass: TEXCLASS.REL }],
  less: ["\u{003C}", { texClass: TEXCLASS.REL }],
  lessapprox: ["\u{2A85}", { texClass: TEXCLASS.REL }],
  lessdot: ["\u{22D6}", { texClass: TEXCLASS.REL }],
  lesseqgtr: ["\u{22DA}", { texClass: TEXCLASS.REL }],
  lesseqqgtr: ["\u{2A8B}", { texClass: TEXCLASS.REL }],
  lessgtr: ["\u{2276}", { texClass: TEXCLASS.REL }],
  lesssim: ["\u{2272}", { texClass: TEXCLASS.REL }],
  lfbowtie: ["\u{29D1}", { texClass: TEXCLASS.REL }],
  lftimes: ["\u{29D4}", { texClass: TEXCLASS.REL }],
  lgE: ["\u{2A91}", { texClass: TEXCLASS.REL }],
  ll: ["\u{226A}", { texClass: TEXCLASS.REL }],
  lll: ["\u{22D8}", { texClass: TEXCLASS.REL }],
  lllnest: ["\u{2AF7}", { texClass: TEXCLASS.REL }],
  lnapprox: ["\u{2A89}", { texClass: TEXCLASS.REL }],
  lneq: ["\u{2A87}", { texClass: TEXCLASS.REL }],
  lneqq: ["\u{2268}", { texClass: TEXCLASS.REL }],
  lnsim: ["\u{22E6}", { texClass: TEXCLASS.REL }],
  longdashv: ["\u{27DE}", { texClass: TEXCLASS.REL }],
  longleftarrow: ["\u{27F5}", { texClass: TEXCLASS.REL }],
  longleftrightarrow: ["\u{27F7}", { texClass: TEXCLASS.REL }],
  longleftsquigarrow: ["\u{2B33}", { texClass: TEXCLASS.REL }],
  longmapsfrom: ["\u{27FB}", { texClass: TEXCLASS.REL }],
  longmapsto: ["\u{27FC}", { texClass: TEXCLASS.REL }],
  longrightarrow: ["\u{27F6}", { texClass: TEXCLASS.REL }],
  longrightsquigarrow: ["\u{27FF}", { texClass: TEXCLASS.REL }],
  looparrowleft: ["\u{21AB}", { texClass: TEXCLASS.REL }],
  looparrowright: ["\u{21AC}", { texClass: TEXCLASS.REL }],
  lrtriangleeq: ["\u{29E1}", { texClass: TEXCLASS.REL }],
  lsime: ["\u{2A8D}", { texClass: TEXCLASS.REL }],
  lsimg: ["\u{2A8F}", { texClass: TEXCLASS.REL }],
  lsqhook: ["\u{2ACD}", { texClass: TEXCLASS.REL }],
  ltcc: ["\u{2AA6}", { texClass: TEXCLASS.REL }],
  ltcir: ["\u{2A79}", { texClass: TEXCLASS.REL }],
  ltlarr: ["\u{2976}", { texClass: TEXCLASS.REL }],
  ltquest: ["\u{2A7B}", { texClass: TEXCLASS.REL }],
  ltrivb: ["\u{29CF}", { texClass: TEXCLASS.REL }],
  mapsdown: ["\u{21A7}", { texClass: TEXCLASS.REL }],
  mapsfrom: ["\u{21A4}", { texClass: TEXCLASS.REL }],
  mapsto: ["\u{21A6}", { texClass: TEXCLASS.REL }],
  mapsup: ["\u{21A5}", { texClass: TEXCLASS.REL }],
  mathratio: ["\u{2236}", { texClass: TEXCLASS.REL }],
  measeq: ["\u{225E}", { texClass: TEXCLASS.REL }],
  mid: ["\u{2223}", { texClass: TEXCLASS.REL }],
  midcir: ["\u{2AF0}", { texClass: TEXCLASS.REL }],
  mlcp: ["\u{2ADB}", { texClass: TEXCLASS.REL }],
  models: ["\u{22A7}", { texClass: TEXCLASS.REL }],
  multimap: ["\u{22B8}", { texClass: TEXCLASS.REL }],
  multimapinv: ["\u{27DC}", { texClass: TEXCLASS.REL }],
  nLeftarrow: ["\u{21CD}", { texClass: TEXCLASS.REL }],
  nLeftrightarrow: ["\u{21CE}", { texClass: TEXCLASS.REL }],
  nRightarrow: ["\u{21CF}", { texClass: TEXCLASS.REL }],
  nVDash: ["\u{22AF}", { texClass: TEXCLASS.REL }],
  nVdash: ["\u{22AE}", { texClass: TEXCLASS.REL }],
  nVleftarrow: ["\u{21FA}", { texClass: TEXCLASS.REL }],
  nVleftarrowtail: ["\u{2B3A}", { texClass: TEXCLASS.REL }],
  nVleftrightarrow: ["\u{21FC}", { texClass: TEXCLASS.REL }],
  nVrightarrow: ["\u{21FB}", { texClass: TEXCLASS.REL }],
  nVrightarrowtail: ["\u{2915}", { texClass: TEXCLASS.REL }],
  nVtwoheadleftarrow: ["\u{2B35}", { texClass: TEXCLASS.REL }],
  nVtwoheadleftarrowtail: ["\u{2B3D}", { texClass: TEXCLASS.REL }],
  nVtwoheadrightarrow: ["\u{2901}", { texClass: TEXCLASS.REL }],
  nVtwoheadrightarrowtail: ["\u{2918}", { texClass: TEXCLASS.REL }],
  napprox: ["\u{2249}", { texClass: TEXCLASS.REL }],
  nasymp: ["\u{226D}", { texClass: TEXCLASS.REL }],
  ncong: ["\u{2247}", { texClass: TEXCLASS.REL }],
  ne: ["\u{2260}", { texClass: TEXCLASS.REL }],
  nearrow: ["\u{2197}", { texClass: TEXCLASS.REL }],
  nequiv: ["\u{2262}", { texClass: TEXCLASS.REL }],
  neswarrow: ["\u{2922}", { texClass: TEXCLASS.REL }],
  ngeq: ["\u{2271}", { texClass: TEXCLASS.REL }],
  ngtr: ["\u{226F}", { texClass: TEXCLASS.REL }],
  ngtrless: ["\u{2279}", { texClass: TEXCLASS.REL }],
  ngtrsim: ["\u{2275}", { texClass: TEXCLASS.REL }],
  nhpar: ["\u{2AF2}", { texClass: TEXCLASS.REL }],
  ni: ["\u{220B}", { texClass: TEXCLASS.REL }],
  niobar: ["\u{22FE}", { texClass: TEXCLASS.REL }],
  nis: ["\u{22FC}", { texClass: TEXCLASS.REL }],
  nisd: ["\u{22FA}", { texClass: TEXCLASS.REL }],
  nleftarrow: ["\u{219A}", { texClass: TEXCLASS.REL }],
  nleftrightarrow: ["\u{21AE}", { texClass: TEXCLASS.REL }],
  nleq: ["\u{2270}", { texClass: TEXCLASS.REL }],
  nless: ["\u{226E}", { texClass: TEXCLASS.REL }],
  nlessgtr: ["\u{2278}", { texClass: TEXCLASS.REL }],
  nlesssim: ["\u{2274}", { texClass: TEXCLASS.REL }],
  nmid: ["\u{2224}", { texClass: TEXCLASS.REL }],
  nni: ["\u{220C}", { texClass: TEXCLASS.REL }],
  notin: ["\u{2209}", { texClass: TEXCLASS.REL }],
  nparallel: ["\u{2226}", { texClass: TEXCLASS.REL }],
  nprec: ["\u{2280}", { texClass: TEXCLASS.REL }],
  npreccurlyeq: ["\u{22E0}", { texClass: TEXCLASS.REL }],
  nrightarrow: ["\u{219B}", { texClass: TEXCLASS.REL }],
  nsim: ["\u{2241}", { texClass: TEXCLASS.REL }],
  nsime: ["\u{2244}", { texClass: TEXCLASS.REL }],
  nsimeq: ["\u{2244}", { texClass: TEXCLASS.REL }],
  nsqsubseteq: ["\u{22E2}", { texClass: TEXCLASS.REL }],
  nsqsupseteq: ["\u{22E3}", { texClass: TEXCLASS.REL }],
  nsubset: ["\u{2284}", { texClass: TEXCLASS.REL }],
  nsubseteq: ["\u{2288}", { texClass: TEXCLASS.REL }],
  nsucc: ["\u{2281}", { texClass: TEXCLASS.REL }],
  nsucccurlyeq: ["\u{22E1}", { texClass: TEXCLASS.REL }],
  nsupset: ["\u{2285}", { texClass: TEXCLASS.REL }],
  nsupseteq: ["\u{2289}", { texClass: TEXCLASS.REL }],
  ntrianglelefteq: ["\u{22EC}", { texClass: TEXCLASS.REL }],
  ntrianglerighteq: ["\u{22ED}", { texClass: TEXCLASS.REL }],
  nvDash: ["\u{22AD}", { texClass: TEXCLASS.REL }],
  nvLeftarrow: ["\u{2902}", { texClass: TEXCLASS.REL }],
  nvLeftrightarrow: ["\u{2904}", { texClass: TEXCLASS.REL }],
  nvRightarrow: ["\u{2903}", { texClass: TEXCLASS.REL }],
  nvartriangleleft: ["\u{22EA}", { texClass: TEXCLASS.REL }],
  nvartriangleright: ["\u{22EB}", { texClass: TEXCLASS.REL }],
  nvdash: ["\u{22AC}", { texClass: TEXCLASS.REL }],
  nvleftarrow: ["\u{21F7}", { texClass: TEXCLASS.REL }],
  nvleftarrowtail: ["\u{2B39}", { texClass: TEXCLASS.REL }],
  nvleftrightarrow: ["\u{21F9}", { texClass: TEXCLASS.REL }],
  nvrightarrow: ["\u{21F8}", { texClass: TEXCLASS.REL }],
  nvrightarrowtail: ["\u{2914}", { texClass: TEXCLASS.REL }],
  nvtwoheadleftarrow: ["\u{2B34}", { texClass: TEXCLASS.REL }],
  nvtwoheadleftarrowtail: ["\u{2B3C}", { texClass: TEXCLASS.REL }],
  nvtwoheadrightarrow: ["\u{2900}", { texClass: TEXCLASS.REL }],
  nvtwoheadrightarrowtail: ["\u{2917}", { texClass: TEXCLASS.REL }],
  nwarrow: ["\u{2196}", { texClass: TEXCLASS.REL }],
  nwsearrow: ["\u{2921}", { texClass: TEXCLASS.REL }],
  origof: ["\u{22B6}", { texClass: TEXCLASS.REL }],
  parallel: ["\u{2225}", { texClass: TEXCLASS.REL }],
  parsim: ["\u{2AF3}", { texClass: TEXCLASS.REL }],
  partialmeetcontraction: ["\u{2AA3}", { texClass: TEXCLASS.REL }],
  perp: ["\u{27C2}", { texClass: TEXCLASS.REL }],
  pitchfork: ["\u{22D4}", { texClass: TEXCLASS.REL }],
  prec: ["\u{227A}", { texClass: TEXCLASS.REL }],
  precapprox: ["\u{2AB7}", { texClass: TEXCLASS.REL }],
  preccurlyeq: ["\u{227C}", { texClass: TEXCLASS.REL }],
  preceq: ["\u{2AAF}", { texClass: TEXCLASS.REL }],
  preceqq: ["\u{2AB3}", { texClass: TEXCLASS.REL }],
  precnapprox: ["\u{2AB9}", { texClass: TEXCLASS.REL }],
  precneq: ["\u{2AB1}", { texClass: TEXCLASS.REL }],
  precneqq: ["\u{2AB5}", { texClass: TEXCLASS.REL }],
  precnsim: ["\u{22E8}", { texClass: TEXCLASS.REL }],
  precsim: ["\u{227E}", { texClass: TEXCLASS.REL }],
  propto: ["\u{221D}", { texClass: TEXCLASS.REL }],
  prurel: ["\u{22B0}", { texClass: TEXCLASS.REL }],
  pullback: ["\u{27D3}", { texClass: TEXCLASS.REL }],
  pushout: ["\u{27D4}", { texClass: TEXCLASS.REL }],
  questeq: ["\u{225F}", { texClass: TEXCLASS.REL }],
  revnmid: ["\u{2AEE}", { texClass: TEXCLASS.REL }],
  rfbowtie: ["\u{29D2}", { texClass: TEXCLASS.REL }],
  rftimes: ["\u{29D5}", { texClass: TEXCLASS.REL }],
  rightarrow: ["\u{2192}", { texClass: TEXCLASS.REL }],
  rightarrowapprox: ["\u{2975}", { texClass: TEXCLASS.REL }],
  rightarrowbackapprox: ["\u{2B48}", { texClass: TEXCLASS.REL }],
  rightarrowbar: ["\u{21E5}", { texClass: TEXCLASS.REL }],
  rightarrowbsimilar: ["\u{2B4C}", { texClass: TEXCLASS.REL }],
  rightarrowdiamond: ["\u{291E}", { texClass: TEXCLASS.REL }],
  rightarrowgtr: ["\u{2B43}", { texClass: TEXCLASS.REL }],
  rightarrowonoplus: ["\u{27F4}", { texClass: TEXCLASS.REL }],
  rightarrowplus: ["\u{2945}", { texClass: TEXCLASS.REL }],
  rightarrowshortleftarrow: ["\u{2942}", { texClass: TEXCLASS.REL }],
  rightarrowsimilar: ["\u{2974}", { texClass: TEXCLASS.REL }],
  rightarrowsupset: ["\u{2B44}", { texClass: TEXCLASS.REL }],
  rightarrowtail: ["\u{21A3}", { texClass: TEXCLASS.REL }],
  rightarrowtriangle: ["\u{21FE}", { texClass: TEXCLASS.REL }],
  rightarrowx: ["\u{2947}", { texClass: TEXCLASS.REL }],
  rightbkarrow: ["\u{290D}", { texClass: TEXCLASS.REL }],
  rightcurvedarrow: ["\u{2933}", { texClass: TEXCLASS.REL }],
  rightdbltail: ["\u{291C}", { texClass: TEXCLASS.REL }],
  rightdotarrow: ["\u{2911}", { texClass: TEXCLASS.REL }],
  rightdowncurvedarrow: ["\u{2937}", { texClass: TEXCLASS.REL }],
  rightfishtail: ["\u{297D}", { texClass: TEXCLASS.REL }],
  rightharpoondown: ["\u{21C1}", { texClass: TEXCLASS.REL }],
  rightharpoondownbar: ["\u{2957}", { texClass: TEXCLASS.REL }],
  rightharpoonsupdown: ["\u{2964}", { texClass: TEXCLASS.REL }],
  rightharpoonup: ["\u{21C0}", { texClass: TEXCLASS.REL }],
  rightharpoonupbar: ["\u{2953}", { texClass: TEXCLASS.REL }],
  rightharpoonupdash: ["\u{296C}", { texClass: TEXCLASS.REL }],
  rightimply: ["\u{2970}", { texClass: TEXCLASS.REL }],
  rightleftarrows: ["\u{21C4}", { texClass: TEXCLASS.REL }],
  rightleftharpoons: ["\u{21CC}", { texClass: TEXCLASS.REL }],
  rightleftharpoonsdown: ["\u{2969}", { texClass: TEXCLASS.REL }],
  rightleftharpoonsup: ["\u{2968}", { texClass: TEXCLASS.REL }],
  rightrightarrows: ["\u{21C9}", { texClass: TEXCLASS.REL }],
  rightsquigarrow: ["\u{21DD}", { texClass: TEXCLASS.REL }],
  righttail: ["\u{291A}", { texClass: TEXCLASS.REL }],
  rightthreearrows: ["\u{21F6}", { texClass: TEXCLASS.REL }],
  rightwavearrow: ["\u{219D}", { texClass: TEXCLASS.REL }],
  risingdotseq: ["\u{2253}", { texClass: TEXCLASS.REL }],
  rsqhook: ["\u{2ACE}", { texClass: TEXCLASS.REL }],
  rtriltri: ["\u{29CE}", { texClass: TEXCLASS.REL }],
  ruledelayed: ["\u{29F4}", { texClass: TEXCLASS.REL }],
  scurel: ["\u{22B1}", { texClass: TEXCLASS.REL }],
  searrow: ["\u{2198}", { texClass: TEXCLASS.REL }],
  shortdowntack: ["\u{2ADF}", { texClass: TEXCLASS.REL }],
  shortlefttack: ["\u{2ADE}", { texClass: TEXCLASS.REL }],
  shortrightarrowleftarrow: ["\u{2944}", { texClass: TEXCLASS.REL }],
  shortuptack: ["\u{2AE0}", { texClass: TEXCLASS.REL }],
  sim: ["\u{223C}", { texClass: TEXCLASS.REL }],
  sime: ["\u{2243}", { texClass: TEXCLASS.REL }],
  simeq: ["\u{2243}", { texClass: TEXCLASS.REL }],
  simgE: ["\u{2AA0}", { texClass: TEXCLASS.REL }],
  simgtr: ["\u{2A9E}", { texClass: TEXCLASS.REL }],
  similarleftarrow: ["\u{2B49}", { texClass: TEXCLASS.REL }],
  similarrightarrow: ["\u{2972}", { texClass: TEXCLASS.REL }],
  simlE: ["\u{2A9F}", { texClass: TEXCLASS.REL }],
  simless: ["\u{2A9D}", { texClass: TEXCLASS.REL }],
  simminussim: ["\u{2A6C}", { texClass: TEXCLASS.REL }],
  simneqq: ["\u{2246}", { texClass: TEXCLASS.REL }],
  simrdots: ["\u{2A6B}", { texClass: TEXCLASS.REL }],
  smallin: ["\u{220A}", { texClass: TEXCLASS.REL }],
  smallni: ["\u{220D}", { texClass: TEXCLASS.REL }],
  smeparsl: ["\u{29E4}", { texClass: TEXCLASS.REL }],
  smile: ["\u{2323}", { texClass: TEXCLASS.REL }],
  smt: ["\u{2AAA}", { texClass: TEXCLASS.REL }],
  smte: ["\u{2AAC}", { texClass: TEXCLASS.REL }],
  sqsubset: ["\u{228F}", { texClass: TEXCLASS.REL }],
  sqsubseteq: ["\u{2291}", { texClass: TEXCLASS.REL }],
  sqsubsetneq: ["\u{22E4}", { texClass: TEXCLASS.REL }],
  sqsupset: ["\u{2290}", { texClass: TEXCLASS.REL }],
  sqsupseteq: ["\u{2292}", { texClass: TEXCLASS.REL }],
  sqsupsetneq: ["\u{22E5}", { texClass: TEXCLASS.REL }],
  stareq: ["\u{225B}", { texClass: TEXCLASS.REL }],
  subedot: ["\u{2AC3}", { texClass: TEXCLASS.REL }],
  submult: ["\u{2AC1}", { texClass: TEXCLASS.REL }],
  subrarr: ["\u{2979}", { texClass: TEXCLASS.REL }],
  subset: ["\u{2282}", { texClass: TEXCLASS.REL }],
  subsetapprox: ["\u{2AC9}", { texClass: TEXCLASS.REL }],
  subsetdot: ["\u{2ABD}", { texClass: TEXCLASS.REL }],
  subseteq: ["\u{2286}", { texClass: TEXCLASS.REL }],
  subseteqq: ["\u{2AC5}", { texClass: TEXCLASS.REL }],
  subsetneq: ["\u{228A}", { texClass: TEXCLASS.REL }],
  subsetneqq: ["\u{2ACB}", { texClass: TEXCLASS.REL }],
  subsetplus: ["\u{2ABF}", { texClass: TEXCLASS.REL }],
  subsim: ["\u{2AC7}", { texClass: TEXCLASS.REL }],
  subsub: ["\u{2AD5}", { texClass: TEXCLASS.REL }],
  subsup: ["\u{2AD3}", { texClass: TEXCLASS.REL }],
  succ: ["\u{227B}", { texClass: TEXCLASS.REL }],
  succapprox: ["\u{2AB8}", { texClass: TEXCLASS.REL }],
  succcurlyeq: ["\u{227D}", { texClass: TEXCLASS.REL }],
  succeq: ["\u{2AB0}", { texClass: TEXCLASS.REL }],
  succeqq: ["\u{2AB4}", { texClass: TEXCLASS.REL }],
  succnapprox: ["\u{2ABA}", { texClass: TEXCLASS.REL }],
  succneq: ["\u{2AB2}", { texClass: TEXCLASS.REL }],
  succneqq: ["\u{2AB6}", { texClass: TEXCLASS.REL }],
  succnsim: ["\u{22E9}", { texClass: TEXCLASS.REL }],
  succsim: ["\u{227F}", { texClass: TEXCLASS.REL }],
  supdsub: ["\u{2AD8}", { texClass: TEXCLASS.REL }],
  supedot: ["\u{2AC4}", { texClass: TEXCLASS.REL }],
  suphsol: ["\u{27C9}", { texClass: TEXCLASS.REL }],
  suphsub: ["\u{2AD7}", { texClass: TEXCLASS.REL }],
  suplarr: ["\u{297B}", { texClass: TEXCLASS.REL }],
  supmult: ["\u{2AC2}", { texClass: TEXCLASS.REL }],
  supset: ["\u{2283}", { texClass: TEXCLASS.REL }],
  supsetapprox: ["\u{2ACA}", { texClass: TEXCLASS.REL }],
  supsetdot: ["\u{2ABE}", { texClass: TEXCLASS.REL }],
  supseteq: ["\u{2287}", { texClass: TEXCLASS.REL }],
  supseteqq: ["\u{2AC6}", { texClass: TEXCLASS.REL }],
  supsetneq: ["\u{228B}", { texClass: TEXCLASS.REL }],
  supsetneqq: ["\u{2ACC}", { texClass: TEXCLASS.REL }],
  supsetplus: ["\u{2AC0}", { texClass: TEXCLASS.REL }],
  supsim: ["\u{2AC8}", { texClass: TEXCLASS.REL }],
  supsub: ["\u{2AD4}", { texClass: TEXCLASS.REL }],
  supsup: ["\u{2AD6}", { texClass: TEXCLASS.REL }],
  swarrow: ["\u{2199}", { texClass: TEXCLASS.REL }],
  toea: ["\u{2928}", { texClass: TEXCLASS.REL }],
  tona: ["\u{2927}", { texClass: TEXCLASS.REL }],
  topfork: ["\u{2ADA}", { texClass: TEXCLASS.REL }],
  tosa: ["\u{2929}", { texClass: TEXCLASS.REL }],
  towa: ["\u{292A}", { texClass: TEXCLASS.REL }],
  trianglelefteq: ["\u{22B4}", { texClass: TEXCLASS.REL }],
  triangleq: ["\u{225C}", { texClass: TEXCLASS.REL }],
  trianglerighteq: ["\u{22B5}", { texClass: TEXCLASS.REL }],
  twoheaddownarrow: ["\u{21A1}", { texClass: TEXCLASS.REL }],
  twoheadleftarrow: ["\u{219E}", { texClass: TEXCLASS.REL }],
  twoheadleftarrowtail: ["\u{2B3B}", { texClass: TEXCLASS.REL }],
  twoheadleftdbkarrow: ["\u{2B37}", { texClass: TEXCLASS.REL }],
  twoheadmapsfrom: ["\u{2B36}", { texClass: TEXCLASS.REL }],
  twoheadmapsto: ["\u{2905}", { texClass: TEXCLASS.REL }],
  twoheadrightarrow: ["\u{21A0}", { texClass: TEXCLASS.REL }],
  twoheadrightarrowtail: ["\u{2916}", { texClass: TEXCLASS.REL }],
  twoheaduparrow: ["\u{219F}", { texClass: TEXCLASS.REL }],
  twoheaduparrowcircle: ["\u{2949}", { texClass: TEXCLASS.REL }],
  typecolon: ["\u{2982}", { texClass: TEXCLASS.REL }],
  uparrow: ["\u{2191}", { texClass: TEXCLASS.REL }],
  uparrowbarred: ["\u{2909}", { texClass: TEXCLASS.REL }],
  updownarrow: ["\u{2195}", { texClass: TEXCLASS.REL }],
  updownarrows: ["\u{21C5}", { texClass: TEXCLASS.REL }],
  updownharpoonleftleft: ["\u{2951}", { texClass: TEXCLASS.REL }],
  updownharpoonleftright: ["\u{294D}", { texClass: TEXCLASS.REL }],
  updownharpoonrightleft: ["\u{294C}", { texClass: TEXCLASS.REL }],
  updownharpoonrightright: ["\u{294F}", { texClass: TEXCLASS.REL }],
  updownharpoonsleftright: ["\u{296E}", { texClass: TEXCLASS.REL }],
  upfishtail: ["\u{297E}", { texClass: TEXCLASS.REL }],
  upharpoonleft: ["\u{21BF}", { texClass: TEXCLASS.REL }],
  upharpoonleftbar: ["\u{2960}", { texClass: TEXCLASS.REL }],
  upharpoonright: ["\u{21BE}", { texClass: TEXCLASS.REL }],
  upharpoonrightbar: ["\u{295C}", { texClass: TEXCLASS.REL }],
  upharpoonsleftright: ["\u{2963}", { texClass: TEXCLASS.REL }],
  upin: ["\u{27D2}", { texClass: TEXCLASS.REL }],
  upuparrows: ["\u{21C8}", { texClass: TEXCLASS.REL }],
  vBar: ["\u{2AE8}", { texClass: TEXCLASS.REL }],
  vBarv: ["\u{2AE9}", { texClass: TEXCLASS.REL }],
  vDash: ["\u{22A8}", { texClass: TEXCLASS.REL }],
  vDdash: ["\u{2AE2}", { texClass: TEXCLASS.REL }],
  varVdash: ["\u{2AE6}", { texClass: TEXCLASS.REL }],
  varisinobar: ["\u{22F6}", { texClass: TEXCLASS.REL }],
  varisins: ["\u{22F3}", { texClass: TEXCLASS.REL }],
  varniobar: ["\u{22FD}", { texClass: TEXCLASS.REL }],
  varnis: ["\u{22FB}", { texClass: TEXCLASS.REL }],
  vartriangle: ["\u{25B5}", { texClass: TEXCLASS.REL }],
  vartriangleleft: ["\u{22B2}", { texClass: TEXCLASS.REL }],
  vartriangleright: ["\u{22B3}", { texClass: TEXCLASS.REL }],
  vbrtri: ["\u{29D0}", { texClass: TEXCLASS.REL }],
  vdash: ["\u{22A2}", { texClass: TEXCLASS.REL }],
  vdots: ["\u{22EE}", { texClass: TEXCLASS.REL }],
  veeeq: ["\u{225A}", { texClass: TEXCLASS.REL }],
  veeonwedge: ["\u{2A59}", { texClass: TEXCLASS.REL }],
  vlongdash: ["\u{27DD}", { texClass: TEXCLASS.REL }],
  wedgeq: ["\u{2259}", { texClass: TEXCLASS.REL }],
});

new CommandMap(
  "unicode-math-macros",
  {
    // \mathaccent
    acute: ["Accent", "0301"],
    annuity: ["Accent", "20E7"],
    asteraccent: ["Accent", "20F0"],
    bar: ["Accent", "0304"],
    breve: ["Accent", "0306"],
    candra: ["Accent", "0310"],
    check: ["Accent", "030C"],
    ddddot: ["Accent", "20DC"],
    dddot: ["Accent", "20DB"],
    ddot: ["Accent", "0308"],
    dot: ["Accent", "0307"],
    droang: ["Accent", "031A"],
    grave: ["Accent", "0300"],
    hat: ["Accent", "0302"],
    leftharpoonaccent: ["Accent", "20D0"],
    ocirc: ["Accent", "030A"],
    ocommatopright: ["Accent", "0315"],
    oturnedcomma: ["Accent", "0312"],
    overbar: ["Accent", "0305"],
    ovhook: ["Accent", "0309"],
    rightharpoonaccent: ["Accent", "20D1"],
    // tilde: ['Accent', '0303'], // NOTE disabled to fallback to core MatJax (which does not use  U+0303 combining tilde)
    vec: ["Accent", "20D7"],
    vertoverlay: ["Accent", "20D2"],
    widebridgeabove: ["Accent", "20E9"],
    // \mathaccentwide
    // NOTE disabled to fallback to core MatJax which uses u2190
    // overleftarrow: ['Accent', '20D6', 1],
    overleftharpoon: ["Accent", "21BC", 1],
    // NOTE disabled to fallback to core MatJax which uses u2194
    // overleftrightarrow: ['Accent', '20E1', 1],
    // NOTE disabled to fallback to core MatJax which uses u2192
    // overrightarrow: ['Accent', '20D7', 1],
    overrightharpoon: ["Accent", "21BD", 1],
    widebreve: ["Accent", "0306", 1],
    widecheck: ["Accent", "030C", 1],
    // NOTE disabled to fallback to core MathJax which uses u005E
    // widehat: ['Accent', '0302', 1],
    wideoverbar: ["Accent", "0305", 1],
    // NOTE disabled to fallback to core MathJax which uses u007E
    // widetilde: ['Accent', '0303', 1],
    // \mathaccentoverlay
    notaccent: "Not",
    // \mathbotaccent
    threeunderdot: ["UnderOver", "20E8"],
    // \mathbotaccentwide
    mathunderbar: ["UnderOver", "0332", 1],
    // NOTE disabled to fallback to core MatJax which uses u2190
    // underleftarrow: ['UnderOver', '20EE', 1],
    underleftharpoondown: ["UnderOver", "21BD", 1],
    // NOTE disabled to fallback to core MatJax which uses u2194
    // underleftrightarrow: ['UnderOver', '034D', 1],
    // NOTE disabled to fallback to core MatJax which uses u2192
    // underrightarrow: ['UnderOver', '20EF', 1],
    underrightharpoondown: ["UnderOver", "21C1", 1],
    wideutilde: ["UnderOver", "0330", 1],
    // \mathover
    // overbrace: ['UnderOver', '23DE'],
    overbracket: ["UnderOver", "23B4"], // NOTE also in mathtools core extension, cf. #24
    // overparen: ['UnderOver', '23DC'], // NOTE disabled to fallback to core MatJax
    // \mathunder
    // NOTE disabled to fallback to core MatJax which uses  ['UnderOver', '23DF', 1],
    // underbrace: ['UnderOver', '23DF'],
    underbracket: ["UnderOver", "23B5"], // NOTE also in mathtools core extension, cf. #24
    // underparen: ['UnderOver', '23DD'],// NOTE disabled to fallback to core MatJax
  },
  unicodeMathMethods
);

new DelimiterMap("unicode-math-delimiters", ParseMethods.delimiter, {
  // \mathopen
  "\\Lbrbrak": ["\u{27EC}", { texClass: TEXCLASS.OPEN }],
  "\u{27EC}": ["\u{27EC}", { texClass: TEXCLASS.OPEN }],
  "\\Lparengtr": ["\u{2995}", { texClass: TEXCLASS.OPEN }],
  "\u{2995}": ["\u{2995}", { texClass: TEXCLASS.OPEN }],
  "\\Lvzigzag": ["\u{29DA}", { texClass: TEXCLASS.OPEN }],
  "\u{29DA}": ["\u{29DA}", { texClass: TEXCLASS.OPEN }],
  "\\cuberoot": ["\u{221B}", { texClass: TEXCLASS.OPEN }],
  "\u{221B}": ["\u{221B}", { texClass: TEXCLASS.OPEN }],
  "\\fourthroot": ["\u{221C}", { texClass: TEXCLASS.OPEN }],
  "\u{221C}": ["\u{221C}", { texClass: TEXCLASS.OPEN }],
  "\\lAngle": ["\u{27EA}", { texClass: TEXCLASS.OPEN }],
  "\u{27EA}": ["\u{27EA}", { texClass: TEXCLASS.OPEN }],
  "\\lBrace": ["\u{2983}", { texClass: TEXCLASS.OPEN }],
  "\u{2983}": ["\u{2983}", { texClass: TEXCLASS.OPEN }],
  "\\lBrack": ["\u{27E6}", { texClass: TEXCLASS.OPEN }],
  "\u{27E6}": ["\u{27E6}", { texClass: TEXCLASS.OPEN }],
  "\\lParen": ["\u{2985}", { texClass: TEXCLASS.OPEN }],
  "\u{2985}": ["\u{2985}", { texClass: TEXCLASS.OPEN }],
  "\\langle": ["\u{27E8}", { texClass: TEXCLASS.OPEN }],
  "\u{27E8}": ["\u{27E8}", { texClass: TEXCLASS.OPEN }],
  "\\langledot": ["\u{2991}", { texClass: TEXCLASS.OPEN }],
  "\u{2991}": ["\u{2991}", { texClass: TEXCLASS.OPEN }],
  "\\lbag": ["\u{27C5}", { texClass: TEXCLASS.OPEN }],
  "\u{27C5}": ["\u{27C5}", { texClass: TEXCLASS.OPEN }],
  "\\lblkbrbrak": ["\u{2997}", { texClass: TEXCLASS.OPEN }],
  "\u{2997}": ["\u{2997}", { texClass: TEXCLASS.OPEN }],
  "\\lbrace": ["\u{007B}", { texClass: TEXCLASS.OPEN }],
  "\u{007B}": ["\u{007B}", { texClass: TEXCLASS.OPEN }],
  "\\lbrack": ["\u{005B}", { texClass: TEXCLASS.OPEN }],
  "\u{005B}": ["\u{005B}", { texClass: TEXCLASS.OPEN }],
  "\\lbracklltick": ["\u{298F}", { texClass: TEXCLASS.OPEN }],
  "\u{298F}": ["\u{298F}", { texClass: TEXCLASS.OPEN }],
  "\\lbrackubar": ["\u{298B}", { texClass: TEXCLASS.OPEN }],
  "\u{298B}": ["\u{298B}", { texClass: TEXCLASS.OPEN }],
  "\\lbrackultick": ["\u{298D}", { texClass: TEXCLASS.OPEN }],
  "\u{298D}": ["\u{298D}", { texClass: TEXCLASS.OPEN }],
  "\\lbrbrak": ["\u{2772}", { texClass: TEXCLASS.OPEN }],
  "\u{2772}": ["\u{2772}", { texClass: TEXCLASS.OPEN }],
  "\\lceil": ["\u{2308}", { texClass: TEXCLASS.OPEN }],
  "\u{2308}": ["\u{2308}", { texClass: TEXCLASS.OPEN }],
  "\\lcurvyangle": ["\u{29FC}", { texClass: TEXCLASS.OPEN }],
  "\u{29FC}": ["\u{29FC}", { texClass: TEXCLASS.OPEN }],
  "\\lfloor": ["\u{230A}", { texClass: TEXCLASS.OPEN }],
  "\u{230A}": ["\u{230A}", { texClass: TEXCLASS.OPEN }],
  "\\lgroup": ["\u{27EE}", { texClass: TEXCLASS.OPEN }],
  "\u{27EE}": ["\u{27EE}", { texClass: TEXCLASS.OPEN }],
  "\\llangle": ["\u{2989}", { texClass: TEXCLASS.OPEN }],
  "\u{2989}": ["\u{2989}", { texClass: TEXCLASS.OPEN }],
  "\\llcorner": ["\u{231E}", { texClass: TEXCLASS.OPEN }],
  "\u{231E}": ["\u{231E}", { texClass: TEXCLASS.OPEN }],
  "\\llparenthesis": ["\u{2987}", { texClass: TEXCLASS.OPEN }],
  "\u{2987}": ["\u{2987}", { texClass: TEXCLASS.OPEN }],
  "\\lmoustache": ["\u{23B0}", { texClass: TEXCLASS.OPEN }],
  "\u{23B0}": ["\u{23B0}", { texClass: TEXCLASS.OPEN }],
  "\\longdivision": ["\u{27CC}", { texClass: TEXCLASS.OPEN }],
  "\u{27CC}": ["\u{27CC}", { texClass: TEXCLASS.OPEN }],
  "\\lparen": ["\u{0028}", { texClass: TEXCLASS.OPEN }],
  "\u{0028}": ["\u{0028}", { texClass: TEXCLASS.OPEN }],
  "\\lparenless": ["\u{2993}", { texClass: TEXCLASS.OPEN }],
  "\u{2993}": ["\u{2993}", { texClass: TEXCLASS.OPEN }],
  "\\lvzigzag": ["\u{29D8}", { texClass: TEXCLASS.OPEN }],
  "\u{29D8}": ["\u{29D8}", { texClass: TEXCLASS.OPEN }],
  // NOTE disabled since it breaks stretchy root overline
  // '\\sqrt': ['\u{221A}', { texClass: TEXCLASS.OPEN }],
  "\u{221A}": ["\u{221A}", { texClass: TEXCLASS.OPEN }],
  "\\ulcorner": ["\u{231C}", { texClass: TEXCLASS.OPEN }],
  "\u{231C}": ["\u{231C}", { texClass: TEXCLASS.OPEN }],
  // \mathclose
  "\\Rbrbrak": ["\u{27ED}", { texClass: TEXCLASS.CLOSE }],
  "\u{27ED}": ["\u{27ED}", { texClass: TEXCLASS.CLOSE }],
  "\\Rparenless": ["\u{2996}", { texClass: TEXCLASS.CLOSE }],
  "\u{2996}": ["\u{2996}", { texClass: TEXCLASS.CLOSE }],
  "\\Rvzigzag": ["\u{29DB}", { texClass: TEXCLASS.CLOSE }],
  "\u{29DB}": ["\u{29DB}", { texClass: TEXCLASS.CLOSE }],
  "\\lrcorner": ["\u{231F}", { texClass: TEXCLASS.CLOSE }],
  "\u{231F}": ["\u{231F}", { texClass: TEXCLASS.CLOSE }],
  "\\mathexclam": ["\u{0021}", { texClass: TEXCLASS.CLOSE }],
  "\u{0021}": ["\u{0021}", { texClass: TEXCLASS.CLOSE }],
  "\\rAngle": ["\u{27EB}", { texClass: TEXCLASS.CLOSE }],
  "\u{27EB}": ["\u{27EB}", { texClass: TEXCLASS.CLOSE }],
  "\\rBrace": ["\u{2984}", { texClass: TEXCLASS.CLOSE }],
  "\u{2984}": ["\u{2984}", { texClass: TEXCLASS.CLOSE }],
  "\\rBrack": ["\u{27E7}", { texClass: TEXCLASS.CLOSE }],
  "\u{27E7}": ["\u{27E7}", { texClass: TEXCLASS.CLOSE }],
  "\\rParen": ["\u{2986}", { texClass: TEXCLASS.CLOSE }],
  "\u{2986}": ["\u{2986}", { texClass: TEXCLASS.CLOSE }],
  "\\rangle": ["\u{27E9}", { texClass: TEXCLASS.CLOSE }],
  "\u{27E9}": ["\u{27E9}", { texClass: TEXCLASS.CLOSE }],
  "\\rangledot": ["\u{2992}", { texClass: TEXCLASS.CLOSE }],
  "\u{2992}": ["\u{2992}", { texClass: TEXCLASS.CLOSE }],
  "\\rbag": ["\u{27C6}", { texClass: TEXCLASS.CLOSE }],
  "\u{27C6}": ["\u{27C6}", { texClass: TEXCLASS.CLOSE }],
  "\\rblkbrbrak": ["\u{2998}", { texClass: TEXCLASS.CLOSE }],
  "\u{2998}": ["\u{2998}", { texClass: TEXCLASS.CLOSE }],
  "\\rbrace": ["\u{007D}", { texClass: TEXCLASS.CLOSE }],
  "\u{007D}": ["\u{007D}", { texClass: TEXCLASS.CLOSE }],
  "\\rbrack": ["\u{005D}", { texClass: TEXCLASS.CLOSE }],
  "\u{005D}": ["\u{005D}", { texClass: TEXCLASS.CLOSE }],
  "\\rbracklrtick": ["\u{298E}", { texClass: TEXCLASS.CLOSE }],
  "\u{298E}": ["\u{298E}", { texClass: TEXCLASS.CLOSE }],
  "\\rbrackubar": ["\u{298C}", { texClass: TEXCLASS.CLOSE }],
  "\u{298C}": ["\u{298C}", { texClass: TEXCLASS.CLOSE }],
  "\\rbrackurtick": ["\u{2990}", { texClass: TEXCLASS.CLOSE }],
  "\u{2990}": ["\u{2990}", { texClass: TEXCLASS.CLOSE }],
  "\\rbrbrak": ["\u{2773}", { texClass: TEXCLASS.CLOSE }],
  "\u{2773}": ["\u{2773}", { texClass: TEXCLASS.CLOSE }],
  "\\rceil": ["\u{2309}", { texClass: TEXCLASS.CLOSE }],
  "\u{2309}": ["\u{2309}", { texClass: TEXCLASS.CLOSE }],
  "\\rcurvyangle": ["\u{29FD}", { texClass: TEXCLASS.CLOSE }],
  "\u{29FD}": ["\u{29FD}", { texClass: TEXCLASS.CLOSE }],
  "\\rfloor": ["\u{230B}", { texClass: TEXCLASS.CLOSE }],
  "\u{230B}": ["\u{230B}", { texClass: TEXCLASS.CLOSE }],
  "\\rgroup": ["\u{27EF}", { texClass: TEXCLASS.CLOSE }],
  "\u{27EF}": ["\u{27EF}", { texClass: TEXCLASS.CLOSE }],
  "\\rmoustache": ["\u{23B1}", { texClass: TEXCLASS.CLOSE }],
  "\u{23B1}": ["\u{23B1}", { texClass: TEXCLASS.CLOSE }],
  "\\rparen": ["\u{0029}", { texClass: TEXCLASS.CLOSE }],
  "\u{0029}": ["\u{0029}", { texClass: TEXCLASS.CLOSE }],
  "\\rparengtr": ["\u{2994}", { texClass: TEXCLASS.CLOSE }],
  "\u{2994}": ["\u{2994}", { texClass: TEXCLASS.CLOSE }],
  "\\rrangle": ["\u{298A}", { texClass: TEXCLASS.CLOSE }],
  "\u{298A}": ["\u{298A}", { texClass: TEXCLASS.CLOSE }],
  "\\rrparenthesis": ["\u{2988}", { texClass: TEXCLASS.CLOSE }],
  "\u{2988}": ["\u{2988}", { texClass: TEXCLASS.CLOSE }],
  "\\rvzigzag": ["\u{29D9}", { texClass: TEXCLASS.CLOSE }],
  "\u{29D9}": ["\u{29D9}", { texClass: TEXCLASS.CLOSE }],
  "\\urcorner": ["\u{231D}", { texClass: TEXCLASS.CLOSE }],
  "\u{231D}": ["\u{231D}", { texClass: TEXCLASS.CLOSE }],
  // \mathfence
  "\\Vert": ["\u{2016}", { texClass: TEXCLASS.ORD }],
  "\u{2016}": ["\u{2016}", { texClass: TEXCLASS.ORD }],
  "\\Vvert": ["\u{2980}", { texClass: TEXCLASS.ORD }],
  "\u{2980}": ["\u{2980}", { texClass: TEXCLASS.ORD }],
  "\\vert": ["\u{007C}", { texClass: TEXCLASS.ORD }],
  "\u{007C}": ["\u{007C}", { texClass: TEXCLASS.ORD }],
});

export const configuration = Configuration.create("unicode-math", {
  handler: {
    delimiter: ["unicode-math-delimiters"],
    macro: [
      "unicode-math-macros",
      "unicode-math-delimiters",
      "unicode-math-mathchar0mi",
      "unicode-math-mathchar0mo",
    ],
  },
});
